### ISSUE TITLE
Automatically setup Docker Builds for newly forked repositories

### ISSUE THREAD

**Issue by apeltzer** [nf-core/nf-co.re#100]
An idea that I already thought about a couple of times:

It should be possible to use the DockerHub APIv2 to automatically create a DockerHub repository for that pipeline upon creation.

Sets up:

- repository + correct name (e.g. nfcore/<pipelinename>)
- sets build rules accordingly for branches `master`, `dev`, and a release version. 

Triggers initially on master and dev.

**Comment by apeltzer** [comment]
https://github.com/RyanTheAllmighty/Docker-Hub-API

**Comment by apeltzer** [comment]
Seems not to be really easy or working at all, barely any information on how to do this:

https://docs.docker.com/registry/spec/api/

This is the endpoint of DockerHub: https://registry-1.docker.io/v2/ 

So using the V2 API, we should be able to query it - however, authentication remains a problem for me here. Maybe someone else has an idea.... @nf-core/core

**Comment by ewels** [comment]
The headers for the API auth error look like this: 
![image](https://user-images.githubusercontent.com/465550/62325481-0b642d80-b4ac-11e9-88c2-7fec9e5bc83e.png)

And reference this URL: https://auth.docker.io/token - which gives a massive token. So I guess it has something to do with this.

But before I go down this rabbit hole - I can't see anything in the docs about creating new repos? It's all pushing and pulling images..?

**Comment by ewels** [comment]
😆  https://docs.docker.com/registry/spec/auth/ - ![image](https://user-images.githubusercontent.com/465550/62325875-05228100-b4ad-11e9-989a-ef49c41b7220.png)

**Comment by apeltzer** [comment]
Yeah I think the biggest issue here is as well that this API just defines image interaction(s). What we need, would be the Registry / Hub interaction, which doesn't exist. Or I didn't find it (yet).

**Comment by ewels** [comment]
Best I can find is posts like [this](https://forums.docker.com/t/create-private-dockerhub-repo-via-api/30271) and [this](https://stackoverflow.com/questions/29844420/how-can-i-create-docker-private-repository-via-docker-hub-api) where people are reverse-engineering the APIs used on the dockerhub website. Doesn't really fill me with confidence - I imagine it could be tricky to set up and is likely to break without warning.. 😕

**Comment by ewels** [comment]
Here's an NodeJS package for the API which says it can do it: https://github.com/RyanTheAllmighty/Docker-Hub-API#createrepositoryusername-name-details

Someone has made a PHP version here: https://github.com/realpage/waves (looks like there is a [method](https://github.com/realpage/waves/blob/eb578875fe6b98cbc36cfb50dfb0f7cf49acbcc2/src/DockerHubAdapter.php#L40) for creating a repo). Not been updated for quite a long time, but might be a good place to start...

**Comment by ewels** [comment]
Closing, as I don't think this will ever happen with DockerHub. What is much more likely that we will start hosting images on the GitHub package repository. But that's for another day.
