### ISSUE TITLE
Documentation about the PR reviewing process

### ISSUE THREAD

**Issue by maxulysse** [nf-core/nf-co.re#1035]
Following a discussion with @sateeshperi we figured it would be a good idea to have some documentation/guidelines about how to actually do a review (I'm thinking also with some specifics about modules, pipelines, tools, website, release...)
It would be super helpful for newcomers.

**Comment by maxulysse** [comment]
@mahesh-panchal probably gave some good insight on this idea as well as usual :-D

**Comment by sateeshperi** [comment]
leaving points here...to be structured later...plz add as you see fit @maxulysse @mahesh-panchal @FriederikeHanssen 

`when all checks pass`
* all optional params must go to `$args`
* must include tests for all output including optional
* optimize the software version extraction command if required
* check `meta.yml` for documentation links; patterns of files; 
* check if the bioconda version of tool is latest ?

`when tests fail`
* linting fails
* conda fails
* docker fails

**Comment by mahesh-panchal** [comment]
- Run tool help and check important input ( usually optional ) has not been missed.
- Check module is suitable for offline running, e.g. from secure servers with no Internet. 
- Remove temporary unzipped files ( otherwise benefit is completely mitigated and problem made worse).
- Check all outputs are captured, by running the pytest (e.g. on Gitpod).

**Comment by mahesh-panchal** [comment]
- Check outputs are compressed ( Do we have guidelines for gzip vs bzip2 vs something else?)

**Comment by FriederikeHanssen** [comment]
Good idea. Leaving this here: https://nf-co.re/developers/adding_modules#new-module-guidelines-and-pr-review-checklist

**Comment by mahesh-panchal** [comment]
Don't know where to put this so I'll just drop it here as a reminder, and may be helpful information for reviewing.
When running docker containers, Nextflow changes the `--entrypoint` to `/bin/bash`. Usually for some containers on Biocontainers (and others), the default entrypoint is `/usr/local/env-execute`, which then sets environment variables used by certain programs (e.g. Busco, Merqury). The files need to be sourced again to use them in container setting ( https://github.com/nf-core/modules/pull/1239#issuecomment-1035073695 )
