### ISSUE TITLE
nf-core tutorial improvements

### ISSUE THREAD

**Issue by ggabernet** [nf-core/nf-co.re#1041]
**Is your feature request related to a problem? Please describe.**
Improving and updating the slides of the nf-core tutorial.

**Describe the solution you'd like**
- Updating the slides to follow the current structure of the tutorial.
- Checking that the tutorial is up to date with the latest DSL2 syntax / modules.
- Adding links to more extended tutorials on specific topics on the nf-core website.
- Test the tutorial and track approximately how long each section takes.

**Describe alternatives you've considered**

**Additional context**

**Comment by jwarnn** [comment]
Hello, I am pretty new to Nextflow and just started using it a few weeks ago so I thought I could best be used working on the tutorials. I started with the nf-core tutorial and thought of a nice feature. There are a number of exercises found in the tutorial and I noticed halfway through that sometimes it was taking me some time to figure out the command that completed the exercise so I was thinking up adding a clickable feature that displays the correct command to accomplish the task.

Example:
### Exercise 2 (listing pipelines)

* Use the help flag to print the list command usage
* List all available nf-core pipelines
* Sort pipelines alphabetically, then by popularity (stars) <details ><summary>Answer</summary><br>nf-core list --sort name nf-core list --sort stars</details>
* Fetch one of the pipelines using `nextflow pull`
* Use `nf-core list` to see if the pipeline you pulled is up to date
* Filter pipelines for those that work with RNA
* Save these pipeline details to a JSON file

It would be better if it was inline as well!

**Comment by ggabernet** [comment]
That's a great idea, thanks!

**Comment by jwarnn** [comment]
Footnotes might be a cleaner way to accomplish this:

* Sort pipelines alphabetically, then by popularity (stars)[^1]


[^1]: ``` nf-core list --sort name & nf-core list --sort stars ```

**Comment by jwarnn** [comment]
I think you intended PR #1082.

**Comment by ggabernet** [comment]
Issue solved by #1082
