### ISSUE TITLE
nf-core/modules guidelines missing `when:` requirement

### ISSUE THREAD

**Issue by jfy133** [nf-core/nf-co.re#1044]
The current modules guidelines does not appear to mention the required `when:` statement

https://nf-co.re/developers/adding_modules#new-module-guidelines-and-pr-review-checklist

even though it results in a linting error with nf-core tools when missing.

This should be documented

**Comment by jenmuell** [comment]
There is a small part about the `when:` statement mentioned in the guidelines:

_The process definition MUST NOT change the when statement. when conditions can instead be supplied using the process.ext.when directive in a configuration file.

process {
    withName: 'FOO' {
        ext.when = !params.skip_module
    }
    withName: 'BAR' {
        ext.when = { meta.single_end }
    }
}_
