### ISSUE TITLE
Docs: Parameter schema

### ISSUE THREAD

**Issue by ewels** [nf-core/nf-co.re#1045]
We could really do with some long-form documentation about nf-core parameter schema files.

At the top we can write `DO NOT EDIT MANUALLY, USE "nf-core schema build"` which will help a lot of people.

After that, should talk about:

* General purpose
* Function within pipelines
* Function with `nf-core launch`
* How to use `nf-core schema build` (from scratch and to update)
* API spec of the different JSON schema fields

**Comment by apeltzer** [comment]
+ including the `docs` building that was recently added.

**Comment by jenmuell** [comment]
PR created for nf-core schema build (from scratch and to update) and for the `nf-core schema docs` command https://github.com/nf-core/tools/pull/1926

**Comment by FranBonath** [comment]
can this issue be closed?
