### ISSUE TITLE
Update CPU guidance to not split cores.

### ISSUE THREAD

**Issue by mahesh-panchal** [nf-core/nf-co.re#1053]
**Is your feature request related to a problem? Please describe.**
The current modules guidelines (https://github.com/nf-core/nf-co.re/blob/master/markdown/developers/adding_modules.md#resource-requirements) specify that the number of CPU's should be split among processes involved in the task.
It's been discussed on several occasions that this is suboptimal, as it wastes CPU allocation and cycles, and it's better to
let the operating system handle the cpu sharing. 
- https://nfcore.slack.com/archives/CE56GDKN0/p1628665510012900?thread_ts=1628663269.011900&cid=CE56GDKN0
- https://github.com/nf-core/modules/pull/760
- https://github.com/nf-core/modules/pull/1125#issuecomment-989821336 ~~This was discussed in some issues too but I can't find it right now. @FriederikeHanssen @maxulysse Do you remember where this was?~~

**Describe the solution you'd like**
Remove the guideline to split cpus, and specify that `task.cpus` is supplied unchanged when a process uses multiple cores.  

**Describe alternatives you've considered**

**Additional context**

**Comment by maxulysse** [comment]
@pontus was the one who advised into this direction

**Comment by maxulysse** [comment]
cf: https://github.com/nf-core/modules/pull/1125#issuecomment-989821336

**Comment by mahesh-panchal** [comment]
Thank you

**Comment by maxulysse** [comment]
I knew where it was, but had troubles finding it only with my phone

**Comment by lukbut** [comment]
@mahesh-panchal Can you please confirm that @muffato 's request is in scope with your original ticket?

**Comment by muffato** [comment]
@mahesh-panchal is on parental leave, but maybe @mashehu can advise.

I guess that the original author of that module noticed that `bwa` only needed 1 core, so to make everything sum up nicely, they gave n-1 cores to the other half of the command. I don't know if that should be considered as an exception (and explained) or whether the module should be changed to use `n` cores everywhere

**Comment by lukbut** [comment]
@muffato I've updated (hopefully!) in line with your suggestions, can you take a look please?

**Comment by mahesh-panchal** [comment]
> @mahesh-panchal Can you please confirm that @muffato 's request is in scope with your original ticket?

Hi @lukbut , I'm currently on parental leave. As such, I'm not really available to work on issues at the moment. 

From a quick read, yes, it's in scope.

**Comment by muffato** [comment]
Sorry @lukbut , but there is still a discrepancy between the guidance (_you can specify directly in the command itself e.g. with `${task.cpus}`_) and the code, https://github.com/nf-core/modules/blob/master/modules/nf-core/bwa/sampe/main.nf#L34 , which uses `${task.cpus - 1}`
