### ISSUE TITLE
Bytesize video (and transcription) is out of date

### ISSUE THREAD

**Issue by jfy133** [nf-core/nf-co.re#1067]
I was looking for an old bytesize and noticed quite a few of the more recent ones (>\#23) are often missing the Youtube embed (and also video transcriptions). We should do a pass and update those as necessary.

**Comment by jfy133** [comment]
https://nfcore.slack.com/archives/C02LK5PLN31/p1647330803793629

Might be able to export the CC as transciprtions

**Comment by FranBonath** [comment]
@jfy133 what video transcriptions do you want to add? Do you mean subtitles?

**Comment by mashehu** [comment]
In the early bytesize we have this synced up video transcriptions, eg: https://nf-co.re/events/2021/bytesize-10-institutional-profiles 
Renuka,actually tried to make them more readable. but the autogenerated subtitles are a good enough start (with less time stamps).

**Comment by jfy133** [comment]
Note that these were quite a lot of work. We don't know how much people use them so we could also just make a policy not to support this anymore (or if there is a way to export YouTube auto-generated subtitles and clean these up, that might work...)
