### ISSUE TITLE
Usage docs page missing

### ISSUE THREAD

**Issue by hmenager** [nf-core/nf-co.re#107]
Hello nf-core team,
https://nf-co.re/usage_docs answers with a 404, so I'm letting you know!

**Comment by hmenager** [comment]
Well, a few pages are not there yet
- Nextflow tutorial
- Helper tools
- Guidelines
etc.
 so I guess it's a work in progress. Good luck!

**Comment by apeltzer** [comment]
Where did you find that url ? If I go to the main homepage, the links on top work :-) 

Would be interesting so we can fix the urls !

**Comment by hmenager** [comment]
At the bottom menus:

Getting Started

    Using nf-core
    Available pipelines
    Helper tools
    Nextflow tutorial

**Comment by apeltzer** [comment]
Amazing that you found these - I'll update them to point to the correct subpages :-)

**Comment by apeltzer** [comment]
Fixed, thanks a bunch @hmenager
