### ISSUE TITLE
Create a Nextflow cheatsheet using Markdown

### ISSUE THREAD

**Issue by chlazaris** [nf-core/nf-co.re#1084]
Creation of a Nextflow cheatsheet in Markdown. The idea is to later contribute it to Dash, so that developers are able to use it. This cheatsheet, if good enough, may also be available on the Nextflow webpage.

The document lives here: https://hackmd.io/NBtD0prcTIa9szfJU7Do7Q?both
It is also available on GitHub: https://github.com/chlazaris/Nextflow_training/blob/main/nextflow_cheatsheet.md

**Comment by snafees** [comment]
Looking good so far, maybe adding a bit about modules would be good! Thank you for spearheading this!

**Comment by chlazaris** [comment]
Thank you @snafees! Working on modules at the moment. Happy to get your input when you find some time!

**Comment by chlazaris** [comment]
Welcome to the team @danrlu

**Comment by ggabernet** [comment]
Great idea! Could you link the cheatsheet to this issue so that people can have a look?

**Comment by chlazaris** [comment]
Thank you @ggabernet! I have now added a link for the live document to the original comment. We work on it with @snafees and @danrlu Please feel free to let us know if you can see it and any comments/suggestions are welcome!

**Comment by chlazaris** [comment]
Hello @ggabernet @snafees @danrlu I have now restructured it to make the sections clearer and I made it also available on GitHub. It can be found here: https://github.com/chlazaris/Nextflow_training/blob/main/nextflow_cheatsheet.md
Thank you for your help!

**Comment by chlazaris** [comment]
Thank you @danrlu @snafees and everyone for your contributions! The latest version of the document can be found here:  https://github.com/chlazaris/Nextflow_training/blob/main/nextflow_cheatsheet.md 
I am now closing this for the purpose of the Hackathon but please feel free to contribute ideas/code on GitHub. Thank you!
