### ISSUE TITLE
CI Runs twice on PRs

### ISSUE THREAD

**Issue by Emiller88** [nf-core/nf-co.re#1105]
The Markdown linting runs twice. I think @grst fixed this in modules? And it might get fixed by #1098 ?
![image](https://user-images.githubusercontent.com/20095261/159035919-32a0badc-76d5-40eb-9aa5-43de5e3b2015.png)

**Comment by grst** [comment]
afaict the PR should fix it. 

The CI Runs twice when you have both `pull_request` and `push` triggers activated for all branches.

**Comment by ewels** [comment]
It's not quite the same when it runs twice. For push it runs on the forked code, for pull request it runs on the merged code.

This is the case for most repos. I don't think it's a big issue..? Or rather, methods for preventing it from running twice come with their own issues (tests not running when they would be useful). My preference is to leave it there twice if it's not causing any problems.

**Comment by grst** [comment]
What's the point of running it on anything but the merged code? 
AFAIK, `push` also works for branches of the same repo, not for forks (they would need to enable it the fork settings).
