### ISSUE TITLE
Add parameter type to pipeline Parameters page

### ISSUE THREAD

**Issue by drpatelh** [nf-core/nf-co.re#1106]
The parameter type is defined in the parameter schema but it isn't rendered in the Parameters page on the website. A couple of users have tripped up thinking e.g. the `--trim_nextseq` parameter is boolean when in fact it should be an integer. Be good if this is documented on the website properly.

**Comment by mashehu** [comment]
Should we do it like it is done for the parameter types on the module pages, i.e. "`--$parameter`($type)"?

**Comment by drpatelh** [comment]
Would it be possible to add it as an extra column after the parameter name instead? Would be clearer to see if everything is aligned together properly.

**Comment by mashehu** [comment]
How about something like this (we have limited horizontal screen estate)?
<img width="903" alt="Screenshot 2022-03-23 at 13 47 16" src="https://user-images.githubusercontent.com/6169021/159702869-68746588-31b0-47c3-a0fc-63df82f88c3d.png">

**Comment by drpatelh** [comment]
This is a good compromise 👍🏽
