### ISSUE TITLE
Add section on Making a new release

### ISSUE THREAD

**Issue by apeltzer** [nf-core/nf-co.re#112]
We should have something that documents on how to get a new pipeline properly released. The question pops up quite frequently and is something we could easily document using 2-3 screenshots, e.g. like this:

<img width="1182" alt="Bildschirmfoto 2019-05-06 um 18 02 25" src="https://user-images.githubusercontent.com/2359510/57238401-98bcf080-7029-11e9-9551-670b7feef511.png">
<img width="499" alt="Bildschirmfoto 2019-05-06 um 18 02 29" src="https://user-images.githubusercontent.com/2359510/57238403-9a86b400-7029-11e9-924d-7aee7002f3f9.png">
<img width="981" alt="Bildschirmfoto 2019-05-06 um 18 02 55" src="https://user-images.githubusercontent.com/2359510/57238405-9ce90e00-7029-11e9-964f-7dace52086aa.png">

**Comment by ewels** [comment]
This is now documented in a couple of places:

* https://nf-co.re/developers/release_checklist
* https://nf-co.re/developers/adding_pipelines#making-the-first-release

No screenshots though. Screenshots would be nice 🤔

**Comment by ewels** [comment]
Closing this issue now, if anyone fancies adding screenshots to the above URLs then that would be cool though ✨
