### ISSUE TITLE
Reorganise the different tutorial links

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/nf-co.re#1154]
I find the current side bar slightly confusing because there are different Tutorial sections. From top-to-bottom:  

* Tutorials : Getting started in nf-core, but also partially usage
* Usage tutorials
* Contributing/Tutorials: How to DSL2

Maybe instead combine the top 2 under Usage/tutorials?
![Screenshot 2022-05-06 at 14 34 47](https://user-images.githubusercontent.com/12273093/167132736-7ccdf70c-9b4f-4f65-922b-db15a16012f4.png)

cc @sateeshperi

**Comment by sateeshperi** [comment]
yes, feel a lot of redundant tutorial links

![docs_tree](https://user-images.githubusercontent.com/33637490/167255405-0083e626-9a9f-4452-8a73-cce04851b22c.png)
