### ISSUE TITLE
Link on Webpage does not Work.

### ISSUE THREAD

**Issue by subwaystation** [nf-core/nf-co.re#125]
[https://nf-co.re/adding_pipelines](https://nf-co.re/adding_pipelines) does not work.
Where should it point to?

Thanks!

**Comment by MaxUlysse** [comment]
Shouldn't the link be https://nf-co.re/developers/adding_pipelines ?
Where did you find this link in the first place?

**Comment by apeltzer** [comment]
Yeah it should - if you can let us know where exactly you found it, we can fix this

**Comment by apeltzer** [comment]
Or you fork the repo, fix it and submit a PR if you want to :)

**Comment by apeltzer** [comment]
Ah I see where this is coming from:

https://nf-co.re/tools

contains the README of https://github.com/nf-core/tools, that contained some broken links on the `master` branch and I fixed these on the `dev` branch a couple of weeks ago. Unfortunately, this submodule is of course still targeting the `master` on nf-core/tools. 

I just briefly spoke with @sven1103 about it and we think we could do the following:

- cherry-pick the commits that fixed this and merge them to a separate branch in nf-core/tools
- merge these to `master` as they don't change anything in the code basis and are just affecting docs

Update the submodule afterwards on the webpage and the remaining issues will be gone - ideas thoughts @drpatelh @ewels ?

**Comment by drpatelh** [comment]
@apeltzer Another option is to just create a release of tools. We could maybe resolve and close a couple of the smaller outstanding issues first? I think the link changes can wait for a new release, and it will save you the hassle of creating a new branch etc.

**Comment by apeltzer** [comment]
Maybe a good idea to have more frequent updates on tools yes

**Comment by apeltzer** [comment]
I made a milestone plan for 1.7 release - feel free to drop / add stuff.  https://github.com/nf-core/tools/milestone/2

**Comment by MaxUlysse** [comment]
If we do more frequent updates on tools, can we have tag for the `nfcore/base` image as well?

**Comment by apeltzer** [comment]
Good idea! I just checked and the `nfcore/base` image is already building based on the tag set on GitHub (e.g. 1.4,1.5,1.6). So we kind of have that already, BUT not in the Dockerfiles used by the template or any of the pipelines (which all still use the `nfcore/base:latest`).

<img width="645" alt="Bildschirmfoto 2019-05-16 um 14 27 39" src="https://user-images.githubusercontent.com/2359510/57853725-c6065d00-77e6-11e9-9bbd-05b43c579c48.png">

One could, therefore, bump the base-image in the template with a release of the tools package to the newest version, too? What do you think?

**Comment by MaxUlysse** [comment]
That seems like a good idea

**Comment by drpatelh** [comment]
@apeltzer Are we good to close this issue? Seems like everything has been updated in the new release of `tools`?
