### ISSUE TITLE
"Edit this page on github" button not working

### ISSUE THREAD

**Issue by SPPearce** [nf-core/nf-co.re#1265]
**Describe the bug**
On the website, there is a button in the top right called Edit, with a tooltip of "Edit this page on github"
**To Reproduce**

1. Go to [https://nf-co.re/docs/contributing/modules](https://nf-co.re/docs/contributing/modules)
2. Click on 'Edit' in the top right
3. This gives a 404 for [https://github.com/nf-core/nf-co.re/tree/master/markdown/docs/contributing/modules.md](https://github.com/nf-core/nf-co.re/tree/master/markdown/docs/contributing/modules.md)

**Expected behavior**
The link takes you to the md file, which is: 
[https://github.com/nf-core/nf-co.re/blob/master/markdown/developers/modules.md](https://github.com/nf-core/nf-co.re/blob/master/markdown/developers/modules.md)

There is a soft-link, at [https://github.com/nf-core/nf-co.re/tree/master/markdown/docs](https://github.com/nf-core/nf-co.re/tree/master/markdown/docs) but these don't seem to be working (I think they might need an extra `..`)

I can't find an edit button that does go to the right place.

**Comment by sofiahag** [comment]
Fixed in https://github.com/nf-core/nf-co.re/pull/1684
