### ISSUE TITLE
Broken/missing links for contributing guidelines

### ISSUE THREAD

**Issue by awgymer** [nf-core/nf-co.re#1283]
It appears that all links under [`Requirements`](https://nf-co.re/contributing/guidelines#requirements) on the contributing guidelines page direct to non-existent pages.

e.g.
```
It looks like https://nf-co.re/contributing/requirements/identity_branding doesn't exist. 
```

**Comment by DJevtic-Persida** [comment]
All links on https://nf-co.re/docs/contributing/guidelines#requirements are working correctly on Firefox 111.0.1(64-bit).

**Comment by mribeirodantas** [comment]
Yeah, it's working on my side too!
