### ISSUE TITLE
Typo in the "Step-by-step guide to writing an institutional profile" section

### ISSUE THREAD

**Issue by mribeirodantas** [nf-core/nf-co.re#1308]
**Describe the problem**
Typos on the _[Step-by-step guide to writing an institutional profile](https://nf-co.re/docs/usage/tutorials/step_by_step_institutional_profile)_ section

- [x] _require your to specify_ should be require **you** to specify

The file to update is [here](https://github.com/nf-core/nf-co.re/blob/master/markdown/usage/tutorials/step_by_step_institutional_profile.md).

**Comment by ctuni** [comment]
Typo is solved and branch with the patch merged to `master` branch

**Comment by abhi18av** [comment]
@ctuni , good work!

Just a suggestion for future work, it's a best practice to link the Pull-Request with the associate issue.

**Comment by ctuni** [comment]
@abhi18av thanks for the suggestion! I thought I had done it by commenting the issue on the PR comments but clearly I did not do it correcly. Do you know what have I misses? Thank you!

**Comment by abhi18av** [comment]
No problem @ctuni , you could make use of the "Development" section on the right hand panel to link the relevant PR.

<img width="389" alt="image" src="https://user-images.githubusercontent.com/12799326/194885492-2fed6bb9-29c1-46d3-b4d9-86ec3a111544.png">
