### ISSUE TITLE
Typo in the gitpod "Intro" section

### ISSUE THREAD

**Issue by mribeirodantas** [nf-core/nf-co.re#1312]
**Describe the problem**
Typos on the Gitpod _[Introduction](https://nf-co.re/docs/contributing/gitpod/gitpod_introduction)_ section

- [x] _parellel_ should be **parallel**

The file to update is [here](https://github.com/nf-core/nf-co.re/blob/master/markdown/developers/gitpod/gitpod_introduction.md).

**Comment by kevinpryan** [comment]
Hi @mribeirodantas, thanks for the message, should be ready to review I think! https://github.com/nf-core/nf-co.re/pull/1335
