### ISSUE TITLE
Add search bar to website

### ISSUE THREAD

**Issue by drpatelh** [nf-core/nf-co.re#132]
Not sure how difficult this is going to be or whether it even makes sense! Just tried to find the post that @apeltzer recently added on Singularity bind paths, and had to find the PR I reviewed to pin point it. Some of it could have been common sense to be honest 😎

**Comment by ewels** [comment]
I think a search bar would be great! Maybe on the homepage - could give fast access to specific pipelines (same as the pipeline search filter box), as well as returning results from the website (ie. docs).

I think we should also think about overhauling the docs to give more sensible structuring at some point, but that should be a separate issue.

**Comment by drpatelh** [comment]
Would be nice to add a `No results found` message um when no results are found.

**Comment by ewels** [comment]
Done 👍

**Comment by drpatelh** [comment]
Amazing. Thank you. Looks great 👍
