### ISSUE TITLE
Fix wrongly highlighted words

### ISSUE THREAD

**Issue by Snorkan** [nf-core/nf-co.re#1339]
"Usage is" is highlighted instead of "nf-core schema validate"

- [ ] Remove tick (`) in the beginning of "Usage"

Link to page with issue: https://github.com/nf-core/tools/edit/master/README.md

**Comment by LouisLeNezet** [comment]
Correction done with [#1910](https://github.com/nf-core/tools/pull/1910)

**Comment by mribeirodantas** [comment]
Fixed by https://github.com/nf-core/tools/pull/1910
