### ISSUE TITLE
Death link to dsl2_modules_tutorial.md

### ISSUE THREAD

**Issue by jenmuell** [nf-core/nf-co.re#1382]
**Describe the bug**
Link to the github page of dsl2_modules_tutorial.md is not working

**To Reproduce**

1. Go to https://nf-co.re/docs/contributing/tutorials/dsl2_modules_tutorial
2. Click on Edit
3. Page not found

**Expected behavior**
Page to the github page with the markdown of the tutorial is opening

**Screenshots**

**Browser (please complete the following information):**

- Browser Firefox

**Additional context**
Link has to be changed to https://github.com/nf-core/nf-co.re/blob/master/markdown/developers/tutorials/dsl2_modules_tutorial.md

**Comment by mribeirodantas** [comment]
This is related to https://github.com/nf-core/nf-co.re/pull/1336. I'm closing this one because it'll be solved [apparently] as soon as the Hackathon is finished 😬
