### ISSUE TITLE
Link to API doc broken

### ISSUE THREAD

**Issue by sven1103** [nf-core/nf-co.re#141]
I just realized that the link to the tools API documentation is broken on the nf-co.re website (section tools https://nf-co.re/tools).

**Comment by ewels** [comment]
Ahhh.... I _may_ have just broken the API docs - it might not be the link (I reimplemented how URL routing and 404 errors are handled a few days ago).

I've now totally forgotten how the API docs are handled. Do you have an old URL for any of them kicking around?

**Comment by sven1103** [comment]
They are pushed to an own branch `api-doc` on nf-core tools: https://github.com/nf-core/tools/tree/api-doc/docs/api/_build/html .

I just checked out the branch, locally it renders perfectly. Did you grab and copy the html to the website server? Sorry, I dont remember :(

**Comment by ewels** [comment]
Ok thanks 👌🏻 Can’t remember exactly how it works, I’m sure it’s done on a deploy script somewhere and just needs some tinkering. Will sort it out as soon as I get back to a computer :)

**Comment by sven1103** [comment]
Thank you @ewels ! :)

**Comment by ewels** [comment]
Seems to be working now!
