### ISSUE TITLE
Testimonial sections

### ISSUE THREAD

**Issue by apeltzer** [nf-core/nf-co.re#152]
We should also have a section with testimonials etc pp that we can refer to - e.g. that the German National Sequencing Centers utilize nf-core/nextflow now widely too.... Can we have another section somewhere in "About" maybe for this purpose?

**Comment by ewels** [comment]
Testimonials is a nice section name for it 😄 Could also embed nice tweets etc then, like I did in the early days on the https://multiqc.info homepage..

**Comment by apeltzer** [comment]
https://github.com/nf-core/nf-co.re/pull/155
