### ISSUE TITLE
Stats: GitHub visitors / clones is per-day, not per-week

### ISSUE THREAD

**Issue by drpatelh** [nf-core/nf-co.re#153]
https://nf-co.re/stats#repo_traffic

The plots are currently labelled as "per week" but it seems that the data is actually represented across 3 weeks? This obviously means that the counts would be over a longer period.

**Comment by MaxUlysse** [comment]
"over time" instead?

**Comment by MaxUlysse** [comment]
What I found more disturbing, is when you zoom in having hours instead of date is not that helpful:
![When is that?](https://user-images.githubusercontent.com/1019628/62367526-3725f880-b52a-11e9-8d19-661520019137.png)

**Comment by ewels** [comment]
Ah yeah, you're right - it's per day! https://developer.github.com/v3/repos/traffic/#clones

My bad, sorry.

> When you zoom, having hours instead of date...

This is default behaviour from the plotting library with a date axis. I agree, not ideal but I can't be bothered to fix this sorry. It will grow and grow from now on, so I doubt this level of zoom will often happen in the future..

**Comment by ewels** [comment]
And to clarify: the data will be forever since we started collecting it. I thought that each point was one week, hence the plot title. I agree that the labelling is all a bit confusing though. I'll endeavour to improve it 🙇
