### ISSUE TITLE
Missing nf-core create subcommand docs and template branch

### ISSUE THREAD

**Issue by sven1103** [nf-core/nf-co.re#16]
Currently the docs do not mention the nf-core tools subcommand `create` and the documentation about how to setup the git repo correctly with an additional `TEMPLATE` branch is not referenced anywhere in the docs.

ToDo:

- [x] Add docs for subcommand `create`
- [x] Link to docs for proper git setup

**Comment by alneberg** [comment]
I think you finished the first task and #19 should finish the second one.
