### ISSUE TITLE
Fix Fairsharing link not working

### ISSUE THREAD

**Issue by nvnieuwk** [nf-core/nf-co.re#1607]
The FAIRsharing.org link is broken here: https://nf-co.re/docs/usage/data_management#choosing-a-repository

**Comment by nvnieuwk** [comment]
Same here: https://nf-co.re/docs/usage/data_management#describing-and-organizing-your-data

**Comment by mashehu** [comment]
Can other's reproduce this? They load fine for me

**Comment by nvnieuwk** [comment]
I get a `500` error message when clicking on them. I've no idea what other get

**Comment by nvnieuwk** [comment]
It seems to be a Firefox specific problem, when I tried it on chrome it also worked fine.

**Comment by mashehu** [comment]
works fine on my firefox (110.0.1) 🤔

**Comment by DJevtic-Persida** [comment]
Links are loading correctly on Firefox 111.0.1 (64-bit) on Ubuntu 22.04.2 LTS.
