### ISSUE TITLE
Update new pipeline docs

### ISSUE THREAD

**Issue by nvnieuwk** [nf-core/nf-co.re#1615]
- [x] Fix the link to the `Running with test data` which is currently pointing to `Adding test data` in the table of contents [here](https://nf-co.re/docs/contributing/adding_pipelines#before-you-start)
- [x] Specify the new way of joining the github organization through Slack [here](https://nf-co.re/docs/contributing/adding_pipelines#join-the-community) instead of pointing to a closed issue where you can ask to be added.
- [x] Link to the mailing list [here](https://nf-co.re/docs/contributing/adding_pipelines#join-the-community) isn't working anymore
- [x] Also a broken mailing list at the end [here](https://nf-co.re/docs/contributing/adding_pipelines#putting-the-test-data-on-github)
- [x] I would suggest adding the filename and location in the template for the config that needs to be adjusted [here](https://nf-co.re/docs/contributing/adding_pipelines#setting-up-a-test-workflow)
- [x] This is outdated DSL1 documentation: https://nf-co.re/docs/contributing/adding_pipelines#adding-new-dependencies-to-an-existing-pipeline
- [x] The first point [here](https://nf-co.re/docs/contributing/adding_pipelines#files) describes a `workflow/` folder while it should be `workflows/`
- [x] Some files are no longer present when creating a pipeline and others are missing [here](https://nf-co.re/docs/contributing/adding_pipelines#files)
- [x] Same for the folders [here](https://nf-co.re/docs/contributing/adding_pipelines#directories)
- [x] It is mentioned [here](https://nf-co.re/docs/contributing/adding_pipelines#dsl2-and-modules) that most pipelines are still DSL1, but that's no longer true
- [x] The last block [here](https://nf-co.re/docs/contributing/adding_pipelines#modules) is no longer in the template
- [x] This whole [block](https://nf-co.re/docs/contributing/adding_pipelines#module-parameters) contains a lot of outdated information
- [x] This [block](https://nf-co.re/docs/contributing/adding_pipelines#sample-meta-information) too
- [x] I would suggest adding a reference [here](https://nf-co.re/docs/contributing/adding_pipelines#dsl2-and-modules) to the [main modules documentation](https://nf-co.re/docs/contributing/modules) instead of having all the outdated information there.

**Comment by LouisLeNezet** [comment]
Hi @cezargrig98  it's always good to connect issues and PRs, for example by adding a comment like "fixes issue #xxx". Read more about it [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

**Comment by cezargrig98** [comment]
Thank you @LouisLeNezet  being a first timer doesn't help with understanding gitpod and how it works
Just linked the pull request with the issue
