### ISSUE TITLE
Remove link on Synchronisation

### ISSUE THREAD

**Issue by sofstam** [nf-core/nf-co.re#1623]
[Atom](https://flight-manual.atom.io/using-atom/sections/github-package/#resolve-conflicts) has been archived. We might need to remove the Atom link described here https://nf-co.re/developers/sync#setting-up-a-pipeline-for-syncing-retrospectively

**Comment by DJevtic-Persida** [comment]
d07deab2080ff809bdbbabf567c6d29b4c7e7cf7
Review needed.
