### ISSUE TITLE
Update Atom section on editor plugins page to say that it is archived

### ISSUE THREAD

**Issue by christopher-hakkaart** [nf-core/nf-co.re#1624]
**Update Atom section on editor plugins page to say that it is archived**

- [editor_plugins.md ](https://github.com/nf-core/nf-co.re/blob/master/markdown/developers/editor_plugins.md) has section on ATOM. It is now archived. Some may still be using this so we should keep it for a little longer but it should be made clear that Atom is archived and support will be limited or absent.

**Comment by mashehu** [comment]
I vote for deleting it. Unfortunately, people should move away from Atom 😢 ![](https://media3.giphy.com/media/qH7J4EXzSCmBy/giphy.gif)

**Comment by christopher-hakkaart** [comment]
I'm +1 for deleting the content. This relates to #1623 as well.

**Comment by arimallick** [comment]
Please assign me this issue.

**Comment by FranBonath** [comment]
Hi @GerardoAcquaviva it's always good to connect issues and PRs, for example by adding a comment like "fixes issue #xxx". Read more about it [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

**Comment by gregorysprenger** [comment]
PR https://github.com/nf-core/nf-co.re/pull/1677 for this issue has been accepted.
