### ISSUE TITLE
Add a more specific link and description for cloud compatible page

### ISSUE THREAD

**Issue by christopher-hakkaart** [nf-core/nf-co.re#1630]
The link on the [cloud-compatible](https://github.com/nf-core/nf-co.re/blob/master/markdown/developers/guidelines/recommendations/cloud_compatible.md) page of the docs is ambiguous and IMO unclear.

- Change nf-core template link to https://nf-co.re/tools/#creating-a-new-pipeline
- Change sentence to say "pipelines created with the nf-core template..." (or something similar)

**Comment by arimallick** [comment]
Please assign this issue to me.
