### ISSUE TITLE
Decrease reference to DSL1 in workflow description.

### ISSUE THREAD

**Issue by christopher-hakkaart** [nf-core/nf-co.re#1631]
The workflow description on the [modules page](https://nf-co.re/docs/contributing/modules) references DSL1 heavily. It would be nice to have a description that focuses on DSL2 rather than referencing a DSL which fewer people will be familiar with. 

- Remove or decrease references to DSL1 in https://nf-co.re/docs/contributing/modules#workflow
- Write a description that reflects DSL2 pipelines

**Comment by LouisLeNezet** [comment]
@gregorysprenger Could you link your PR to this issue ?
You can do it by adding a comment as follow "fix #1631"

**Comment by gregorysprenger** [comment]
PR for issue https://github.com/nf-core/nf-co.re/pull/1716
