### ISSUE TITLE
Update tutorial for adding modules to pipelines

### ISSUE THREAD

**Issue by christopher-hakkaart** [nf-core/nf-co.re#1639]
The tutorial for [adding modules to pipelines](https://nf-co.re/docs/contributing/tutorials/adding_modules_to_pipelines) could be improved. It would be good to add some points to encourage prettier and pre-commit before submitting PR.

- Insist prettier should be installed and run
- Is anyone still using VSCode 'Format Document' - maybe it's better to remove this and focus on prettier
- Can add a point about pre-commit and link to bytesize 

Should there be a new tutorial about sub workflows? This could be referenced here but the tutorial name would need to change. 🤔

**Comment by FranBonath** [comment]
fixed with https://github.com/nf-core/nf-co.re/pull/1704
