### ISSUE TITLE
PNG logos generated via website appear to be fuzzy

### ISSUE THREAD

**Issue by drpatelh** [nf-core/nf-co.re#172]
Using this command:
curl https://nf-co.re/logo/nanodemux?w=600 --output nfcore-nanodemux_logo.png

Generates the image below:
![nfcore-nanodemux_logo](https://user-images.githubusercontent.com/23529759/63933233-b981d980-ca50-11e9-9d49-186763b8e95d.png)

**Comment by drpatelh** [comment]
![nfcore-nanodemux_logo](https://user-images.githubusercontent.com/23529759/63934108-82acc300-ca52-11e9-9be3-842aa61337bf.png)

I have now! So its probably something to do with the scaling then.

**Comment by MaxUlysse** [comment]
I guess 600 pixel is too small, 800 seems to be a good starting point, but all our logos have different width, wouldn't it be better to have a sensible fixated height instead ?

**Comment by ewels** [comment]
Yes it’s definitely the scaling. I assumed that the 600px was a good width for the readme that isn’t full width.. It’s not just the width though I think, I think that the process of scaling the image that is making it look crappy.
