### ISSUE TITLE
Not all links in MD are available the website

### ISSUE THREAD

**Issue by MaxUlysse** [nf-core/nf-co.re#175]
I have that in the docs: https://github.com/nf-core/sarek/blob/dev/docs/usage.md#--skipqc
But that won't work in the website: https://nf-co.re/sarek//docs/usage#--skipQC

**Comment by ewels** [comment]
Correct - it appears that if a heading contains only `<code>` then the automatic anchors don't work. I guess the code is stripping HTML tags first, so in this case strips the entire text.

**Comment by ewels** [comment]
Yeah, the problem is this regex: https://github.com/nf-core/nf-co.re/blob/79ebe9c4d5d27df3ca3f3a8fd55472058fe4b5e0/includes/header.php#L73
