### ISSUE TITLE
The Parameters JSON Schema file is missing

### ISSUE THREAD

**Issue by seth-biorad** [nf-core/nf-co.re#177]
I'm getting a 404 for the json schema: https://nf-co.re/parameters.schema.json

**Comment by ewels** [comment]
Yup, it was recently moved so that it’s versioned: https://github.com/nf-core/nf-co.re/pull/174

Out of curiosity, how did you notice? We weren’t sure if anyone would be using it yet..

**Comment by ewels** [comment]
Sorry, should have said - new URL is now https://nf-co.re/params/0.2.0dev/parameters.schema.json

**Comment by seth-biorad** [comment]
Yeah! This is also me: https://github.com/nf-core/rnaseq/issues/266#issuecomment-519288304, I'm using it to drive a gui, and needed to look up the spec and got scared when it didn't exist anymore!
