### ISSUE TITLE
Links to Docs are broken

### ISSUE THREAD

**Issue by danielecook** [nf-core/nf-co.re#186]
https://nf-co.re/rnafusion/rnafusion//usage.md

That link is listed here:

https://nf-co.re/rnafusion/docs

EDIT:
All links to the pipeline docs in the Documentation tabs are broken:
cf:
https://nf-co.re/rnaseq/docs
https://nf-co.re/rnafusion/docs
https://nf-co.re/sarek/docs

**Comment by ewels** [comment]
Good spot! Yes the table of contents links in the box are fine, this is a markdown rendering issue - those links will work on GitHub, just need to get them to work on the website as well..
