### ISSUE TITLE
nf-core has dependencies on conda-forge

### ISSUE THREAD

**Issue by monfortm** [nf-core/nf-co.re#187]
Dear nf-core team,

If one has not pre-configured channels on conda a conda install, the following command from the [tutorial](https://nf-co.re/usage/nf_core_tutorial#installing-the-nf-core-helper-tools) won't run because some dependencies are pulled from conda-forge

```bash
conda install -c bioconda nf-core
```

Use this command instead

```bash
conda install -c bioconda -c conda-forge -c default nf-core
```

Not sure if the default channel is useful here though

Cheers,

M

**Comment by ewels** [comment]
Thanks for this - good spot :+1:

I have updated the docs a little - instead of specifying all of the channels on the command line I've just linked out to the bioconda setup docs. I think that's probably more future proof and safer..

Phil
