### ISSUE TITLE
Request : externalize PR / issues stats

### ISSUE THREAD

**Issue by Lucas-C** [nf-core/nf-co.re#190]
Hi

I have stumbled on your awesome project statistics: https://nf-co.re/stats#github_prs

I find the PR & issues stats especially pretty & useful:

![2019-09-19 17_12_04-nf-core](https://user-images.githubusercontent.com/925560/65257152-0feab100-db01-11e9-825c-b613ddd27697.png)

I don't know of any open-source tool that provides those.

Do you think those graphs could be easily reused for other `git` repos ?
They are based on GitHub API v3 `/repos/statistics` API ?
I had a quick look and the rendering logic seems buried in this 1500+ lines PHP script: [stats.php](https://github.com/nf-core/nf-co.re/blob/master/public_html/stats.php)

**Comment by Lucas-C** [comment]
To be a bit more explicit on this request, I am not asking that you perform any refactoring, I am asking for :
- authorization to re-use parts of this code elsewhere
- some advice/leads on how to extract the code that generates those graphs

**Comment by MaxUlysse** [comment]
@ewels would be the only one able to answer to that, but I do think that you're on the right path, everything should be in this `stats.php` script.
License is MIT, so you should be able to modify/re-use.

**Comment by Lucas-C** [comment]
Thanks !

Ok, is see that [update_issue_stats.php](https://github.com/nf-core/nf-co.re/blob/master/update_issue_stats.php) generates a JSON file which is used for the issues data for those graphs.

**Comment by apeltzer** [comment]
Yeah, we keep these metrics on the webserver at the moment IIRC.

**Comment by ewels** [comment]
Absolutely! Glad you like it and feel free to go ahead and use it. Out of curiosity, what is the project that you have in mind?

Most of this code was written late at night and on a tight deadline for our paper review, so I apologise in advance for the poor code quality. Give us a shout if you run into any problems or have any questions.

Phil

**Comment by Lucas-C** [comment]
Thanks for your answers !

I extracted it as a Python script, as I'm more familiar with this language : https://gist.github.com/Lucas-C/5c9730756e7b3f795c6d121d38a9ce88

I only kept the 2 "Pull Requests" / "Response Times" graphs.
