### ISSUE TITLE
Instructions to pull singularity container not working

### ISSUE THREAD

**Issue by pascal-git** [nf-core/nf-co.re#203]
On https://nf-co.re/usage/installation the instructions to pull the singularity image are not correct. The code there is:

`singularity pull --name nf-core-YOUR_PIPELINE.simg nf-core/YOUR_PIPELINE`

An example of running this code is:
```
pascalp@kingfisher ~ $ singularity pull --name nf-core-rnaseq-1.3.simg nf-core/rnaseq:1.3
FATAL:   While pulling library image: image nf-core/rnaseq:1.3 (amd64) does not exist in the library
```

The correct code example should be:
`singularity pull --name nf-core-YOUR_PIPELINE.img docker://nfcore/YOUR_PIPELINE`

**Comment by drpatelh** [comment]
Closing in favour of https://github.com/nf-core/nf-co.re/issues/206
