### ISSUE TITLE
Singularity pull fails

### ISSUE THREAD

**Issue by ScientistSMC** [nf-core/nf-co.re#206]
Tried to setup Singularity (for offline use) using the instructions in the installation.md file but it failed. See below:

```bash
[user]$ singularity pull --name nf-core-rnaseq-1.3.img docker://nf-core/rnaseq:1.3
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Docker image path: index.docker.io/nf-core/rnaseq:1.3
ERROR UNAUTHORIZED: authentication required
ERROR Check existence, naming, and permissions
Cleaning up...
ERROR: pulling container failed!
```

But I was able to get it working after editing the docker image path to remove the "-" from nf-core based on a similiar issue in another nf-core pipeline (see here: https://github.com/nf-core/chipseq/issues/8). See below:

```bash
[user$ singularity pull --name nfcore-rnaseq-1.3.img docker://nfcore/rnaseq:1.3
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Docker image path: index.docker.io/nfcore/rnaseq:1.3
Cache folder set to /home/samcarli/.singularity/docker
[8/8] |===================================| 100.0% 
Importing: base Singularity environment
...
```

Created a pull request to remove the "-" in the installation.md document.

**Comment by drpatelh** [comment]
@apeltzer @ScientistSMC This indeed needs a fix! See https://github.com/nf-core/nf-co.re/issues/203

Need to create a PR to the website repo asap now that it's been observed twice in a week! :sweat_smile:

**Comment by apeltzer** [comment]
It is a bit weird that the markdown document is already fixed but apparently the webpage didn't update? 

https://github.com/nf-core/nf-co.re/blob/master/markdown/usage/local_installation.md#singularity-image

**Comment by drpatelh** [comment]
Ah, but the bug is in a  different page:
https://github.com/nf-core/nf-co.re/blob/master/markdown/usage/installation.md#singularity

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/nf-co.re/pull/207
