### ISSUE TITLE
Automate GitHub repo settings

### ISSUE THREAD

**Issue by ewels** [nf-core/nf-co.re#210]
At the moment, we manually set repository settings to be consistent. This is getting increasingly difficult, especially when we agree on a new standard and have to do it to a large number of repos.

Instead, we should make use of the awesome GitHub API and automate this to check, and optionally set, these settings.

Repo settings: ([API](https://developer.github.com/v3/repos/#edit))

* [x] Disable wikis
* [x] Enable issues
* [x] ~Disable sponsorships~ - _not easily available from API, I think_
* [x] ~Disable projects~ - _already disabled organisation wide, so I don't think we need to do this_
* [x] Allow merge commits and rebase merging
* [x] Do not allow squash merges
* [x] `master` as default branch
* [x] Keywords must have `nf-core`, `nextflow`, `workflow` and `pipeline` as a minimum.
* [x] Description must be set.
  * Can't create this, but can flag a failure where missing.
* [x] URL should be set to `https://nf-co.re/[PIPELINE-NAME]`
* [x] ~Set social preview~ (depends on https://github.com/nf-core/nf-co.re/issues/176) - _cannot set image via GitHub API_ 
    * *Can’t set this, but we can check if it is set up (if we can fetch the image).*

Repo team settings: ([API](https://developer.github.com/v3/teams/#add-or-update-team-repository))

* [x] Write access for nf-core/all
* [x] Admin access for nf-core/core

Repo branch settings: ([API](https://developer.github.com/v3/repos/branches/#update-branch-protection))

* [x] `master` rules:
    * Require 2 approving reviews for merge
        * Allow nf-core/core to dismiss reviews
    * Require status checks to pass before merging
        * If GitHub actions, check all tests
        * Travis if present, dockerhub
    * Restrict who can push to matching branches (all)
* [x] `dev` rules: As for `master`, except:
    * Only 1 approving review needed for merge

_[Edit - added]_ Release statuses:

* [x] Highlighting pipelines that are still in dev (and sort by this)
* [x] Test if there has been a release after the latest nf-core/tools release
    * ie. if pipeline has latest template features

Need to think a little about where to put this code. I guess that having it on the website makes most sense, so that it be triggered by a web hook whenever new repositories are added.

We could also make a page around it to show repo "health" where we flag any settings that are wrong. We could also have warning statuses, for stuff like descriptions that are too long or too short, or repos that don't have enough keywords. Kind of like linting for everything that's not in the repo files. This page could then have a button to fix a repo / all repos on demand. I guess this page, or at least these buttons, should be hidden behind a password for admins only.

❓ Thoughts on whether the health page should be public?

**Comment by apeltzer** [comment]
If we don't have potentially malicious stuff, we can keep it open I think ?

**Comment by ewels** [comment]
Reopening - https://nf-co.re/pipelines now shows health, but no option to automatically fix things yet.
