### ISSUE TITLE
wrong file path in quick start guide

### ISSUE THREAD

**Issue by FranBonath** [nf-core/nf-co.re#212]
in 
nf-cor-re/public_html/index.php
line 146: ```mv nextflow ~/bin```

needs to be changed to (at least) ```mv nextflow ~/bin/```

**Comment by ewels** [comment]
Code in question:
https://github.com/nf-core/nf-co.re/blob/master/public_html/index.php#L146

Please make a PR! Something this small you can do in the web editor, probably quicker than making the issue 😅

**Comment by ewels** [comment]
(good spot by the way 👍 )

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/nf-co.re/pull/213
