### ISSUE TITLE
Problems while setting up the local version of the website

### ISSUE THREAD

**Issue by mashehu** [nf-core/nf-co.re#218]
While I was working on #215, I I ran into the following problems, not (fully) covered in the readme:
- github access token from `conf.ini` is needed for `$ php update_pipeline_details.php` (ran otherwise into the github api limit), but that is only mentioned later
- there is no specification of permissions the github access token in `conf.ini` needs
- when running `$ php update_stats.php` I got an error for the  https://api.github.com/repos/nf-core/ampliseq/traffic/views forbidden error with “Must have push access to repository."

**Comment by ewels** [comment]
Yes, all good points. Apologies, this is due to me being the only person working on the website until now (mostly late nights over the summer).

Docs PR welcome if you managed to resolve all of this stuff 👍

**Comment by ewels** [comment]
Note that the new `pipeline_health.php` page requires way more user permissions that most other pages in order to fully work, as it resets repository settings for all repos.
