### ISSUE TITLE
Automated broken link checks ? 

### ISSUE THREAD

**Issue by apeltzer** [nf-core/nf-co.re#236]
https://github.com/gaurav-nelson/github-action-markdown-link-check

Maybe worth checking ?

**Comment by FriederikeHanssen** [comment]
I tried this for rnaseq pipeline and it works reasonable well:

name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        fetch-depth: 1
    - uses: gaurav-nelson/github-action-markdown-link-check@0.4.0

**Comment by ewels** [comment]
@FriederikeHanssen - do you have a PR open for this somewhere?

**Comment by FriederikeHanssen** [comment]
@ewels not yet, still working on it

**Comment by ewels** [comment]
Note that we can (a) have these tests on both `push` and `pull_request` and (b) limit to only events that change markdown files. See the markdown linting as an example:
https://github.com/nf-core/nf-co.re/blob/59225cbb20445f26a2b60ca79ec35c00d1862d33/.github/workflows/markdown.yml#L2-L6

**Comment by FriederikeHanssen** [comment]
cool thanks.

**Comment by ewels** [comment]
In fact, it might make most sense to add this link checking to the same workflow as above. Can just be an additional step / job.

**Comment by FriederikeHanssen** [comment]
Yes, I agree. Will do that

**Comment by ewels** [comment]
Hi @FriederikeHanssen, any movement on this issue?

**Comment by FriederikeHanssen** [comment]
@ewels the proposed package does not support to check for section links. I opened an issue [there](https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/11) . So far no reply. I guess we could move forward without this specific check for now. TBH I wanted to finish it right after the hackathon and then got derailed by other stuff. I should have some time on Friday afternoon to finish this up

**Comment by ewels** [comment]
Maybe we can use [remark lint](https://github.com/remarkjs/remark-lint) instead. It seems to have two plugins that can handle both soft headings links as well as external links:

https://github.com/remarkjs/remark-validate-links
https://github.com/davidtheclark/remark-lint-no-dead-urls

**Comment by gaurav-nelson** [comment]
@FriederikeHanssen Do you have a PR for this already? I must have marked `Unwatch` on GitHub so I wasn't getting any notifications about it. I am back again now, if you put up a PR (for nf-co.re) we can work together on it and try to configure and use markdown-link-check action. 

Also, it does check for internal links and images as well.
