### ISSUE TITLE
Automatically tweet about pipeline releases

### ISSUE THREAD

**Issue by ewels** [nf-core/nf-co.re#24]
It would be nice if we can make use of the GitHub web hook to detect new pipeline releases and automatically tweet about them. Should be relatively easy if we use https://twitteroauth.com/ (can have https://github.com/abraham/twitteroauth as a git submodule).

Cool features would be:

* [x] Usernames and passwords stored in a config file as with the other stuff already
* [x] A check to make sure that it's a pipeline (ignore other listed repos)
* [x] Fire only on releases and not other events
* [x] Skip pre-releases and release candidates
* [x] Link to the release page
* [ ] Check for existing tweets linking to the same URL??
* [x] Add in some information about the pipeline (use description?)
* [ ] Link to the main nf-core website
* [ ] Have a list of available templates so that it's not the same message every time
* [ ] Emoji 😀 

Any other ideas..?

**Comment by alneberg** [comment]
What passwords do you want to store in a config file? Just for a nf-core twitter account?

**Comment by ewels** [comment]
Yup! We already have a setup for this where we save the GitHub hook key so that we know that the we hook payloads are authentic: https://github.com/nf-core/nf-co.re/blob/master/config_example.ini

**Comment by alneberg** [comment]
I see. I just got some internal security alarm bells going off when I read the first point. But I guess the damage would be quite small if those keys would be stolen.

**Comment by MaxUlysse** [comment]
- [ ] Post a different groot gif with each release

**Comment by apeltzer** [comment]
The tweets work really well now - been running for weeks now, so I think we can close this :-) If @MaxUlysse is eager, find a random groot gif generator and add it in a different issue ;-)
