### ISSUE TITLE
Make a page to list publications

### ISSUE THREAD

**Issue by ewels** [nf-core/nf-co.re#261]
We have quite a few publications that are related to the nf-core project now. It would be great to have a page listing them!

* nf-core/lncpipe
  * > Qi Zhao, Yu Sun, Dawei Wang, Hongwan Zhang, Kai Yu, Jian Zheng, Zhixiang Zuo. LncPipe: A Nextflow-based pipeline for identification and analysis of long non-coding RNAs from RNA-Seq data. J Genet Genomics. 2018 Jul 20;45(7):399-401
* nf-core/mhcquant
  * > MHCquant: Automated and Reproducible Data Analysis for Immunopeptidomics
Leon Bichmann, Annika Nelde, Michael Ghosh, Lukas Heumos, Christopher Mohr, Alexander Peltzer, Leon Kuchenbecker, Timo Sachsenberg, Juliane S. Walz, Stefan Stevanović, Hans-Georg Rammensee, and Oliver Kohlbacher
Journal of Proteome Research 2019 18 (11), 3876-3884
DOI: 10.1021/acs.jproteome.9b00313
* Nature article about workflow managers (mentioning nf-core)
  * Nature 573, 149-150 (2019) - doi: 10.1038/d41586-019-02619-z
* nf-core/sarek
  * > Garcia M, Juhos S, Larsson M et al. Sarek: A portable workflow for whole-genome sequencing analysis of germline and somatic variants [version 1; peer review: awaiting peer review]. F1000Research 2020, 9:63 (https://doi.org/10.12688/f1000research.16665.1)
* nf-core preprint / final publication 😱 

@likelet / @Leon-Bichmann / @MaxUlysse - everyone happy for the above papers to be listed on the nf-core website?

Did I miss any..?

**Comment by MaxUlysse** [comment]
Good idea, I'm all for it

**Comment by Leon-Bichmann** [comment]
Sure sounds great!

**Comment by likelet** [comment]
great!
