### ISSUE TITLE
Update 'Adding a new pipeline': travis -> GitHub Actions

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/nf-co.re#262]
If I understand correctly, it was agreed to use GitHub Actions instead of travis in the future. So the section about setting up travis should probably be updated.

**Comment by drpatelh** [comment]
Yep. Good spot :+1: Although we havent officially switched completely yet. That will happen after the next release of `tools`.
https://nf-co.re/developers/adding_pipelines#set-up-travis-and-docker-hub

**Comment by ewels** [comment]
Better still - I think it can just be deleted! No need to "set up" GitHub actions, it's done automatically when you fork / upload a repo with the actions config files I believe..

**Comment by ewels** [comment]
Solved ✅
