### ISSUE TITLE
Fix links in the Contributor Leaderboard

### ISSUE THREAD

**Issue by MaxUlysse** [nf-core/nf-co.re#270]
cf #269
- [ ] `nanodemux` is still listed in the contributor leaderboard, but its name is now `nanoseq`, but there is no redirection for https://nf-co.re/nanodemux to https://nf-co.re/nanoseq
- [ ] `nf-co.re` is listed, but it doesn't have any page, so this link https://nf-co.re/nf-co.re leads to nowhere
- [ ] same for `configs` : https://nf-co.re/configs

**Comment by mashehu** [comment]
Has been fixed, can't find specific PR which did it.
