### ISSUE TITLE
Missing md files in the pipeline page

### ISSUE THREAD

**Issue by MaxUlysse** [nf-core/nf-co.re#271]
cf #269 
- [ ] `CONTRIBUTING.md`: https://nf-co.re/sarek/.github/CONTRIBUTING -> https://github.com/nf-core/sarek/blob/master/.github/CONTRIBUTING.md
- [ ] `CHANGELOG.md`: https://nf-co.re/sarek/CHANGELOG -> https://github.com/nf-core/sarek/blob/master/CHANGELOG.md
- [ ] `CITATIONS.md`: https://nf-co.re/atacseq/CITATIONS -> https://github.com/nf-core/atacseq/blob/master/CITATIONS.md

**Comment by ewels** [comment]
Won't fix this now that https://github.com/nf-core/nf-co.re/pull/456 is implemented, but the 404 errors that these give now suggest the correct GitHub URL 👍🏻 

---

<img src="https://user-images.githubusercontent.com/465550/88855794-abee4a00-d1f3-11ea-8238-3f9c5e9a0538.png" width=400>
