### ISSUE TITLE
low contrast for marker background color in dark mode

### ISSUE THREAD

**Issue by mashehu** [nf-core/nf-co.re#287]
Before I started to write a pull request I wanted to hear your opinions about my solution.

When using the site search functionality in dark mode the results' contrast should be enhanced:
<img width="823" alt="Screenshot 2020-02-14 10 00 30" src="https://user-images.githubusercontent.com/6169021/74517130-e730e100-4f11-11ea-9b51-d7730616556d.png">

My proposal would be to increase the opacity of the marker color (to 1 in this example): 
<img width="743" alt="Screenshot 2020-02-14 10 07 17" src="https://user-images.githubusercontent.com/6169021/74517092-d5e7d480-4f11-11ea-9a46-497f5997e5f3.png">

PS: maybe we should also come up with a consistent spelling/capitalization for Docker Hub. 😉

**Comment by MaxUlysse** [comment]
Good point, it does indeed look more clear, and I'll suggest `DockerHub` as the spelling we should adopt.

**Comment by mashehu** [comment]
On their website they write it `Docker Hub`: https://docs.docker.com/docker-hub/

**Comment by ewels** [comment]
How does it look if you instead _drop_ the opacity?

**Comment by mashehu** [comment]
With an opacity of 0.1 the text-background contrast gets better for the marker area gets better, but for me the marker get's more difficult to see. 
<img width="695" alt="Screenshot 2020-02-18 09 26 44" src="https://user-images.githubusercontent.com/6169021/74717599-fa54f100-5230-11ea-8b60-2e7f7b7605a2.png">
I checked now how it is handled in light mode and there the marker-to-page-backround contrast is actually very low. So a lower opacity would follow more the light mode.

**Comment by ewels** [comment]
Yeah, that was what I was thinking. I personally prefer this - the highlighting isn't very important and I find the high opacity version a little distracting, makes the text harder to read.

**Comment by mashehu** [comment]
Before I push the changes, I would like to point out one  edge case. When you are searching for something which is in a code tag, the marker highlight is really difficult to make out (you can see the difference between the marker and the code background in the left and right padding): 
<img width="722" alt="Screenshot 2020-02-18 10 19 23" src="https://user-images.githubusercontent.com/6169021/74721807-3c356580-5238-11ea-91c2-b01c54b5d031.png">
Here with the old settings:
<img width="712" alt="Screenshot 2020-02-18 10 19 33" src="https://user-images.githubusercontent.com/6169021/74721796-38a1de80-5238-11ea-9cd5-a6dcc0c18f9c.png">

Are you okay with that or should I keep it at 0.3 for `code>mark` elements?

**Comment by ewels** [comment]
I'm ok with it being difficult to make out in code 👍
