### ISSUE TITLE
Add SSL certificate

### ISSUE THREAD

**Issue by matq007** [nf-core/nf-co.re#30]
I just realized that the domain doesn't have SSL certificate. We could use [Let's encrypt](https://letsencrypt.org/). It's free and they already have a bot that renews the certificate every three months.

**Comment by ewels** [comment]
They do, but sadly the bot doesn't work on shared hosting running using cPanel. The site is currently running on my personal hosting and I would have to manually renew it every three months. I'll check back in with my hosting provider to ask whether there are any new options. Alternatively, we can of course shift the hosting onto one of our in-house servers.

**Comment by matq007** [comment]
What if we setup a cron job for that? cPanel should have this option.

**Comment by ewels** [comment]
Cron jobs are ok, I looked into this back in 2016. The problem was that I needed the command line tools installed - quoting my past self:

> Looking at https://certbot.eff.org I think we're ok on Python dependencies (it supports 2.6) but it needs the "EPEL (Extra Packages for Enterprise Linux) repository" which requires a `sudo` command.

As it required `sudo` I couldn't do it, and I gave up.

If there are any new packages able to do this which run with like, zero package requirements, then I can certainly take a look again 👍 

Python 2.7.5 (default, Jul  3 2018, 12:19:32)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2

**Comment by pditommaso** [comment]
Amazon S3 + CloudFront, they also provide SSL certificate.

**Comment by HadrienG** [comment]
Could that be what you are looking for: <https://documentation.cpanel.net/display/CKB/The+Let%27s+Encrypt+Plugin> ?

**Comment by ewels** [comment]
Yes exactly, but the provider of my shared hosting needs to install that for me. I asked them in 2016 and again today, probably a no but they've escalated it so we'll see what they say. They [charge a fair amount](https://hostpresto.com/ssl-certificates/) for managing SSL certs, so I'm not really surprised that they don't want to install a WHM plugin which would let people do it themselves for free.

If we think this is a big enough problem we can move the site to a different server.

**Comment by MaxUlysse** [comment]
Who's your provider?

**Comment by matq007** [comment]
My only solution then would be to use Cloudflare's free [plan](https://www.cloudflare.com/plans/). We just have to make some workaround ...

**Comment by ewels** [comment]
meh, would probably be more work than just moving to a different server. Which would be almost no work in fact - it's ridiculously easy to deploy, not even any database. Just clone the repo on a LAMP server and copy the yaml config file with the keys, then update the domain DNS.

Thumbs up / down as to whether you think the SSL issue is important enough to warrant doing this.. :)

**Comment by apeltzer** [comment]
Sven and I have an (own) maintained web server running which we keep up2date anyways. If you want we can set up a virtual host environment and you'd only need to set up DNS on your side at some point. 

As we're already running certbot etc on that server anyway, it would be fairly easy to set this up. Traffic is not an issue as the page doesn't host tons of things anyways and the server is quite powerful.

**Comment by ewels** [comment]
My web host provider has succumbed to my requests and installed support for LetsEncrypt! Fingers crossed, we should hopefully have a valid SSL certificate from tomorrow...

**Comment by apeltzer** [comment]
![NICE](https://media.giphy.com/media/m745dTCAxerHa/giphy.gif)
