### ISSUE TITLE
Add the possibility to see dev docs on the website

### ISSUE THREAD

**Issue by MaxUlysse** [nf-core/nf-co.re#309]
Currently https://nf-co.re/sarek/docs is the `master` docs if the pipeline is released or else `dev`.
It could be good to have https://nf-co.re/sarek/docs/dev or https://nf-co.re/sarek/dev/docs for released pipelines so that we can see dev docs with the nice rendering we have on the nf-core website.

**Comment by MaxUlysse** [comment]
Actually, it could be good to have docs for specific versions as well

**Comment by drpatelh** [comment]
Think this is a good idea too 👍

**Comment by ewels** [comment]
Keen to do this 👍 I would suggest a slightly different URL scheme though, as `docs` is actually just a folder in the repo, so not strictly standardised. My suggestion would be:

* if a file or directory path after the pipeline name is found on `master` branch, render it. Takes priority.
  * `https://nf-co.re/sarek/docs`
  * `https://nf-co.re/sarek/docs/usage.md`
* `https://nf-co.re/sarek/1.3.2/docs` - if no match, check to see if first URL part after the pipeline name is a release tag or branch name. If it is, try to match the remaining to a file path.
  * `https://nf-co.re/sarek/1.3.2/docs`
  * `https://nf-co.re/sarek/dev/docs/usage.md`

**Comment by ewels** [comment]
Done in https://github.com/nf-core/nf-co.re/pull/456
