### ISSUE TITLE
Extend search function to include pipeline docs

### ISSUE THREAD

**Issue by mashehu** [nf-core/nf-co.re#314]
It would be useful, especially while developing a new pipepline, to be able to search through the documentation of all pipelines from the website.

We had a short discussion about it and @ewels brought up the following, which points to good starting points for a PR:
> The pipeline docs are currently fetched from GitHub dynamically when you try to access them (unless there is already a cached copy)
So the search would only be searching the cached docs, or we'd have to use the GitHub API to do the search remotely somehow.
Or we change how the pipeline docs work, so that we cache all docs for all pipelines as soon as a new pipeline is forked or released

**Comment by MaxUlysse** [comment]
To add more information on that, I'll mention #309 as I feel it's connected

**Comment by mashehu** [comment]
@ewels: The second option sound easier to me at the moment, but could you clarify how the caching is done currenlty. I tried to go through the code, but didn't figure yet out, where it is specified what is cached or is `pipelines.json` the cache you meant?

**Comment by ewels** [comment]
Yes it's a bit hidden sorry - pipeline docs are handled in this script: https://github.com/nf-core/nf-co.re/blob/master/includes/pipeline_page/docs.php

**Comment by ewels** [comment]
Should be covered by https://github.com/nf-core/nf-co.re/issues/1024
