### ISSUE TITLE
Confusing navigation sidebar

### ISSUE THREAD

**Issue by mashehu** [nf-core/nf-co.re#316]
I find the sidebar on the docs page a bit confusing, because it is incomplete/redundant with respect to the horizontal nav-tabs and not in agreement with the doc's TOC:
<img width="1206" alt="Screenshot 2020-02-28 10 36 08 copy" src="https://user-images.githubusercontent.com/6169021/75537631-aeb3fb80-5a17-11ea-9f14-a378de7fcb0c.png">

My proposal would be to remove the readme and documentation bullets and basically have the complete TOC as a sidebar on every subpage.

From a user's perspective it is also a bit confusing when you talk about files in the first line, when they appear as pages to them.

**Comment by ewels** [comment]
Switched `files` > `pages` in the template in nf-core/tools#569

Suggestion to simplify the side-nav:

* Exclude `README` (can't remember why I left this here)
* If `Docs` is only top-level item, hide and show child notes as top level instead.

This should remove the duplication of _Readme_ and _Documentation_ at least..

**Comment by ewels** [comment]
Replaced in https://github.com/nf-core/nf-co.re/pull/456
