### ISSUE TITLE
Make params-builder that uses JSON Schema

### ISSUE THREAD

**Issue by ewels** [nf-core/nf-co.re#322]
Once the other parts of the puzzle are in place for JSON Schema, and pipelines start to have valid JSON Schema present, we can offer a "params-builder" for each pipeline in the website. Users can fill in the different fields and get a params JSON / nextflow config file to download and run with the pipeline.

**Comment by combiz** [comment]
Have a basic concept here: https://combiz.github.io/nf-core-scflow/ , a self-contained index.html file using standard JSON schema to auto-generate a form (some previous discussions here: https://github.com/nextflow-io/nextflow/issues/866).  Clicking submit generates the `nfx-params.json` which works without issues with `-params-file`.  

Could potentially drop the index.html file into the docs folder and have github pages host the params builder page for each pipeline.

Ideally, it would read the json from `parameters.settings.json`?

**Comment by apeltzer** [comment]
Where does the pipeline get the JSON from at the moment? The main Github Repo that hosts the pipeline...? 

Yeah, if we can generalize this to read e.g. a docs, one could even integrate this with the main nf-core webpage, where users can select per drop down (open for discussion ...?) which pipeline they would like to generate a config for, select the release / tag of that pipeline and then the GUI will do what you just show for scflow - looks pretty much amazing already - thanks for sharing this!

**Comment by combiz** [comment]
Yes, a default set of JSON parameters is included in the pipeline as `conf/nfx-params.json` and the JSON schema was manually created and pasted into the index.html file above.  This should be in its own file ideally.  

I agree it would be neat to have a generalized params builder tool on the nf-core webpage where a JSON schema file is read dynamically for a specified pipeline/version to generate a web form.  I used https://ulion.github.io/jsonform/playground/ as the json-schema-to-webform tool here, and @ewels mentioned a few were working out the box (provided the schema meets certain conventions).

**Comment by apeltzer** [comment]
That all sounds like minimum effort - maximum output ...? Or am I missing something here while reading through all  of this again 🤔 ?

**Comment by ewels** [comment]
Yeah, I am planning to make this a standard feature embedded within each pipeline page on the website. I think it should be quite easy - there are tonnes of libraries that can do it. As the rest of the website is built in PHP and I have to fetch the JSON files with that I’ll probably write it in PHP also. Exception might be to use a JavaScript library just to validate the form inputs and generate a download client-side.

Should be pretty nice once we have some schema to play with!

**Comment by ewels** [comment]
Closed in #329
