### ISSUE TITLE
Build params docs from pipeline schema

### ISSUE THREAD

**Issue by ewels** [nf-core/nf-co.re#393]
Use the new JSON schema in pipelines (if present) to build a documentation page for pipeline parameters on the pipeline page.

**Comment by mashehu** [comment]
current ideas:
- split `Documentation` in the navbar into `Usage` and `Output` (maybe find better terms, also maybe replace `Readme` with `Introduction`?)
- move `docs/{usage,output}` to `{usage,output}`
- only render usage.md for pipelines without a json-schema (in a further step, maybe make a lint check that usage.md is removed if nextfow-schema.json is present)
- move schema group names into a navbar sidebar (and maybe make the tab sticky to replicate parts of the current sidebar)

**Comment by ewels** [comment]
Sounds good! Some quick thoughts:

* How about rendering `usage.md` above the automated parameter docs? Then people can write custom prose documentation if they want. Hopefully they will clean the parameters from `usage.md` when making schema..
* If we are updating the URLs for docs, would be great to make them versioned too (#309)

Navbar sidebar is good, some of the ToC stuff we have kicking around looks a bit rubbish, so if you fancy sprucing that generally then that would be fab 👍

**Comment by mashehu** [comment]
Okay, I got the rendering working. 
Concerning which parts of the actual schema to use, I was thinking of using only the help text if available and otherwise drop back to the description, because they are often redundant, with the help text being more in depth.

**Comment by ewels** [comment]
Hmm, no I think we should have both sorry. I’m not sure that we can guarantee that they will duplicate one another that much? And I have a feeling that some I’ve written assume that both will be visible. This is how it’s rendered it on the command line too.

**Comment by ewels** [comment]
Done in https://github.com/nf-core/nf-co.re/pull/456
