### ISSUE TITLE
Make and RSS feed for events

### ISSUE THREAD

**Issue by ewels** [nf-core/nf-co.re#411]
Good for subscribing to in Slack and helping people stay up to date with new things.

Scripting: https://www.w3schools.in/php/php-rss-feed/

**Comment by matq007** [comment]
This could be done also just by parsing event markdown files and generating index.xml each time there is a new deployment?
Here is an [example RSS](https://matq007.github.io/index.xml) generated by Hugo on my page. Then there is no need for the database then?
I can have a look at this. What do you think?

**Comment by ewels** [comment]
Sorry, I didn't mean that we should use a DB, the link was just reference to the RSS XML format.

I think the simplest way is to just create a PHP file that parses the markdown files on the fly and generates the RSS output. No extra files that way, so no added complication around deployment and updates etc. Probably easiest as part of the existing `events.php`.
