### ISSUE TITLE
Launch not possible with released pipelines (?)

### ISSUE THREAD

**Issue by apeltzer** [nf-core/nf-co.re#419]
To Reproduce:

1.) Pick pipeline with existing schema, e.g. atacseq:1.2.0
2.) https://nf-co.re/launch?pipeline=atacseq&release=v1.2.0
3.) Get error:

```
Error - Could not find a pipeline schema for atacseq - v1.2.0
Please launch using the command line tool instead: nf-core launch atacseq -r v1.2.0
```

**Comment by apeltzer** [comment]
<img width="1294" alt="Bildschirmfoto 2020-07-03 um 14 13 09" src="https://user-images.githubusercontent.com/2359510/86468270-5c714700-bd37-11ea-9a0a-d5cebdb19136.png">

**Comment by ewels** [comment]
Should be https://nf-co.re/launch?pipeline=atacseq&release=1.2.0 (Without the `v`)

Works with the button on the atacseq page, it's just the dropdowns on the launch page that need fixing.

**Comment by ewels** [comment]
Fixed ✅
