### ISSUE TITLE
Multi-selection for schema builder

### ISSUE THREAD

**Issue by apeltzer** [nf-core/nf-co.re#422]
It would be speeding things up quite a lot to have some sort of multi-selection available, either via ticking certain parameters and then grouping them at once into a new group. 

Or by being able to select multiple entries and then shifting them together :-)

**Comment by ewels** [comment]
Moved to website repo.

If I remember correctly, multi-selection was tricky during building. Could maybe get around this by using keyboard shortcuts to multi-select (eg. `shift` + `↑`). Add a selected class if so then make the dragging code look for this. Needs some thought either way.

**Comment by ewels** [comment]
Maybe group selection is still going to be a bit insufficient. Might be better to have a dedicated interface (modal?) showing just parameter names which can then be bulk-added to groups.

Maybe show ungrouped top-level params only? Would simplify the new interface a lot..

**Comment by mashehu** [comment]
yes, without adding another js library, the smoothest solution would probbly be a "Add to this group" button on the group header (or the toolbar if a group is selected), with a dropdown/modal with a list of ungrouped params (extra points for filtering the list by search).

**Comment by ewels** [comment]
Yes, nice idea 👍
