### ISSUE TITLE
Launch: Group descriptions not rendering with markdown

### ISSUE THREAD

**Issue by jpfeuffer** [nf-core/nf-co.re#425]
<img width="543" alt="Bildschirmfoto 2020-07-06 um 19 49 26" src="https://user-images.githubusercontent.com/8102638/86625623-a96a4d00-bfc5-11ea-9e19-596fa99ccc31.png">

**Comment by ewels** [comment]
Fixed in 14719c5934f1c27b88e5fad9ad6bf374efe2550f
