### ISSUE TITLE
Launch: section drop-down expands upwards

### ISSUE THREAD

**Issue by jpfeuffer** [nf-core/nf-co.re#426]
At least for me on macOS Chrome. No matter how far I scroll down. So it is only useable when the view is on the very top of the page.
<img width="565" alt="Bildschirmfoto 2020-07-06 um 20 12 47" src="https://user-images.githubusercontent.com/8102638/86625382-4aa4d380-bfc5-11ea-8e6e-fc45e089ebd5.png">

**Comment by ewels** [comment]
Fixed in 6d43fd44216951c9a39215480b68d868f84f6431 [see [diff](https://github.com/nf-core/nf-co.re/commit/6d43fd44216951c9a39215480b68d868f84f6431#diff-0baf5f7d330240ec797bfe3bb5071009L542-R561)]
