### ISSUE TITLE
Website Docker image

### ISSUE THREAD

**Issue by ewels** [nf-core/nf-co.re#446]
At the moment it's a bit of a hassle for people to test out PRs on the website. You need to set up a LAMP / MAMP / WAMP server locally which can put newcomers off.

Even though we won't use it in production, it could be nice to have a simple Docker container to run a server for people to test PRs. Thinking about it, it will have to mount a checked-out version of the code for this, so we can presumably use an existing Docker container and just write an example command in the docs / Readme about how to do this.

Any suggestions / previous experience?

**Comment by mashehu** [comment]
Speaking from trying to set it up locally myself: the biggest issue was getting all the credentials right and comment parts out, where I didn't have them, all related to the different sources for stats, tweets etc. So if we could maybe could put dummy json files and dev tags around other parts it should work.

**Comment by MaxUlysse** [comment]
Honestly, I've tried setting up a LAMP server, which I haven't done in years.
And even if it got way easier that it was, I failed miserably to render the nf-co.re website.
I would definitively like something to help render the website more easilly.

**Comment by mashehu** [comment]
To better replicate the server: which version of php and apache is running on it, @ewels?

**Comment by ewels** [comment]
Awesome! 🚀
