### ISSUE TITLE
JSON Schema - update to new structure

### ISSUE THREAD

**Issue by mashehu** [nf-core/nf-co.re#449]
As described in https://github.com/nf-core/tools/issues/687, the json-schema will look a bit different compared to now.

Files which need to be checked and updated:
- [x] json_schema.php
- [x] ~~json_schema_build.php~~ `pipeline_schema_builder.php`
- [x] launch.php 
- [x] ~~usage.php~~ `docs_schema.php`
- [x] nf-core-schema-builder.js
- [x] nf-core-schema-launcher.js

**Comment by ewels** [comment]
* `json_schema.php` - don't think that there's anything specific here that needs updating
* `pipeline_schema_builder.php` + `nf-core-schema-builder.js` - https://github.com/nf-core/nf-co.re/pull/463

**Comment by ewels** [comment]
* `launch.php` + `nf-core-schema-launcher.js` - https://github.com/nf-core/nf-co.re/pull/466
