### ISSUE TITLE
Schema builder: autosave

### ISSUE THREAD

**Issue by ewels** [nf-core/nf-co.re#488]
It would be nice if the schema builder could automatically save each update as it's made. I could see this happening in one of two ways:

1. We save the JSON schema to the browser local storage each time it changes, and check for this with the cache ID when we load the page.

2. We use a background `POST` API call to actually save the schema each time it updates, but without changing its status. So the same method as when we click _Finished_ except the status. Reloading the page will reload the latest save.

I'm thinking that (2) is probably the easiest to implement and better of the two options.

This should save accidents like the one suffered by @ggabernet where progress is accidentally lost by refreshing the page etc.

**Comment by drpatelh** [comment]
Yes, this would be nice. I got stung yesterday when I clicked a link in the help text and tried to go back to the schema I was updating. Luckily, I had only made a few changes so was able to rescue the situation without having to throw anything across the room.

**Comment by ewels** [comment]
Should be done and merged in #491 - the web copy will now be updated every time you make a change, so refreshing the page or navigating away and back again should be safe. Would be great if someone could test!

PR #490 still open which contains additional functionality to also automatically save changes back to the local file as they are made on the server in real time. @ggabernet / @drpatelh - any thoughts on this? (I’m not completely sure that we really want this behaviour, but would like some additional input).

**Comment by drpatelh** [comment]
Yep, I think it's better to cache the web copy and then only to save locally when "Finished" is clicked. You can imagine instances where someone just wants to "play" with a particular schema without having it saved instantly, especially since it is then not trivial to undo those changes.

**Comment by mashehu** [comment]
git would help with the undo (if the json-schema is tracked already)

**Comment by ggabernet** [comment]
Yes, I agree with Harshil. If there would be a use case where save changes to the local file is also desired, maybe these could be triggered by a Save button, as you were mentioning earlier, rather than automatically in real time.

**Comment by mashehu** [comment]
okay, I'll close PR #490 then and this issue has been successfully addressed by #491.

**Comment by drpatelh** [comment]
To use your analogy in the other PR @mashehu its quite easy to undo with a word processor but having to do this with `git` -> 🤯

**Comment by drpatelh** [comment]
Thank you muchly for this 🙂

**Comment by ewels** [comment]
Yes, thank you @mashehu!

**Comment by ggabernet** [comment]
yes, thanks a lot for the quick fix!
