### ISSUE TITLE
Schema builder drag'n'drop problems

### ISSUE THREAD

**Issue by jpfeuffer** [nf-core/nf-co.re#496]
Not sure if it is just for me, but if I close all groups and try to move a new param that I introduced, it does not stay.

**Comment by jpfeuffer** [comment]
![Bildschirmvideo aufnehmen 2020-08-27 um 17 18 26](https://user-images.githubusercontent.com/8102638/91462130-1ee9ef80-e88a-11ea-8726-bb8f0fcf4b45.gif)

**Comment by jpfeuffer** [comment]
If I open a group and put the param inside, it works.

**Comment by ewels** [comment]
This is a feature, not a bug. You need to drop params into the space in a group, so it doesn’t work when they are collapsed. With the newer schema design ungrouped params must come after all groups, so when you drop a param between two groups it automatically drops back down to below them all.

Does that make sense? We have a new button on the groups to bulk-add params if that helps. Allowing params to be dropped onto collapsed groups is technically tricky I think, sadly.

**Comment by jpfeuffer** [comment]
Aah ok makes sense. I also forgot about the new feature. I actually just wanted to temporarily place the param there to avoid scrolling haha.

**Comment by ewels** [comment]
Yes we should maybe have a little error-message toast that shows briefly in the corner explaining why the param didn't land where you dropped it 🤔
