### ISSUE TITLE
link from events not working

### ISSUE THREAD

**Issue by MaxUlysse** [nf-core/nf-co.re#523]
https://nf-co.re/events refers to https://github.com/nf-core/nf-co.re/blob/master/nf-core-events.yaml
for modification

**Comment by mashehu** [comment]
A bit difficult where this page should actually point to. Maybe [https://github.com/nf-core/nf-co.re/tree/master/markdown/events](https://github.com/nf-core/nf-co.re/tree/master/markdown/events)?

**Comment by ewels** [comment]
Ah yeah, the YAML file is how it used to work. Pointing to that directory would be best I think @mashehu 👍🏻
