### ISSUE TITLE
Tower Launch - use new field names

### ISSUE THREAD

**Issue by ewels** [nf-core/nf-co.re#524]
Nextflow Tower has changed some of the field names, so the submission button needs updating - see https://github.com/seqeralabs/nf-tower-cloud/issues/314#issuecomment-708336778

A new `paramsText` field also means that we can submit JSON directly, so can simplify the code a bit as we already have JSON (can kill [this code](https://github.com/nf-core/nf-co.re/blob/1bd3302f3af2171ea7e0549d525d3fe3e4414bd5/public_html/launch.php#L530-L540)).

**Comment by ewels** [comment]
From @pditommaso on the linked issue:

> @ewels I've realized that we have renamed `configParams` to `configText`, we may have broken something in the nf-core launch form when passing the params to tower.
> 
> Also now the launch form has a new fields `paramsText` that takes the params in json or yaml (the same of NF `-params-file`)

..

> Yes, `paramsText` are only the params in json or yaml, ie.
> 
> ```
> { "foo": "hello" }
> ```
> 
> `configText` is the NF config file therefore
> 
> ```
> params.foo = "hello"
> ```

**Comment by phiweger** [comment]
@ewels could you post an example for a JSON text string that you put in the "paramsText" field? I tried different things but nf tower keeps ignoring the files I want to specify as input to my pipeline. I'm probably just doing something wrong with the expected syntax. Thanks!
