### ISSUE TITLE
add copy-link functionality to parameter names.

### ISSUE THREAD

**Issue by mashehu** [nf-core/nf-co.re#526]
As discussed on [slack](https://nfcore.slack.com/archives/CE5LG7WMB/p1602751619086500).

**Comment by ewels** [comment]
![Oct-15-2020 13-04-50](https://user-images.githubusercontent.com/465550/96115316-0a6bc000-0ee7-11eb-9885-07df6e407a83.gif)

Example markup:

https://github.com/nf-core/nf-co.re/blob/4a458011ccbd1b7a6f5d11713f37b698b7abbfb6/public_html/stats.php#L235

**Comment by drpatelh** [comment]
Yup. Thats perfect 👍

**Comment by mashehu** [comment]
The correct elements are actually already in place (thanks to `add_ids_to_headers()`), the problem is they are behind some other elements and I can't figure which or how to display them correctly. 
Maybe related to that: the link behavior is also a bit different between the `.header-link` elements in from the usage.md vs the once in the schema-docs part. The margin/padding trick somehow doesn't work for the latter, so the href scrolls them up to the top of the window behind the navbar instead of just underneath it 😕
