### ISSUE TITLE
Render default values for parameters obtained via the JSON schema

### ISSUE THREAD

**Issue by drpatelh** [nf-core/nf-co.re#528]
Would be nice to see what the default values for each parameter wherever they are rendered on the website too. These values are already in the JSON file and are used with the launch functionality already.

**Comment by mashehu** [comment]
On what level should they be shown? Always visible or as part of the help text?

**Comment by drpatelh** [comment]
Sorry, would need some screenshots to see what you mean 🙂

**Comment by ewels** [comment]
I think always visible... 🤔 But needs experimentation probably.

**Comment by mashehu** [comment]
First design experiments:
<img width="1108" alt="Screenshot 2020-10-18 at 11 18 18" src="https://user-images.githubusercontent.com/6169021/96363334-e9e47580-1133-11eb-8944-32a28ed0290d.png">
