### ISSUE TITLE
Add Tutorial / HowTo Section?

### ISSUE THREAD

**Issue by apeltzer** [nf-core/nf-co.re#53]
Phil had the idea to also provide a tutorial/howto section on the webpage, since we have quite some material available now!

**Comment by ewels** [comment]
x-ref https://github.com/nf-core/tools/issues/291

To start with, just a copy+paste job of all pipeline-generic documentation from the template to the website. Replace in the template with a link to those docs. Need to read through everything to make sure it makes sense.

Made a start on this, including a simpler mechanism for adding new docs pages, here: https://github.com/nf-core/nf-co.re/pull/87

**Comment by ewels** [comment]
Tutorial here: https://nf-co.re/usage/nf_core_tutorial and a _lot_ of documentation added since this issue was created. Closing in favour of more specific issues.
