### ISSUE TITLE
Minor bug: s3 results explorer

### ISSUE THREAD

**Issue by ewels** [nf-core/nf-co.re#551]
Minor bug: if a directory does not contain any paths, the view does not update when clicking the directory (the path a the top docs).

See for example https://nf-co.re/atacseq/example_output#atacseq/results-1b3a832db5a53c92c2c89a4d6d79455e860461ad/

![Nov-03-2020 14-06-44](https://user-images.githubusercontent.com/465550/97988815-d7c63080-1ddd-11eb-984b-c0ed2f7c30a6.gif)

**Comment by mashehu** [comment]
Sorry, I can't reproduce this, because the directory you link to is not empty any more and I can't find any similar ones at the moment...
