### ISSUE TITLE
Mini HowTo add institution / yourself to community?

### ISSUE THREAD

**Issue by apeltzer** [nf-core/nf-co.re#552]
Our community page has nice links / descriptions on how to join the organization, but not really much except "Is your group missing? Please submit a pull request to add yourself! It's just a few lines in a simple YAML file.." 

Proposal: 

- Add a step-by-step guide on how to do this properly 
    - YAML edit
    - add two images (and how to get them properly shaped...)

Add this to the join page would also make it easier for us to simply link to this when people comment on the #3 

Thoughts / ideas?

**Comment by MaxUlysse** [comment]
I like this idea, would be good to have a dedicated page on the website for that, plus what actually needs to be done, because I think we add comments on #3 too

**Comment by ewels** [comment]
I was sure that there was already an issue about this from way back when, but I can't find it.

But yes, I have had this in the back of my mind for a long time. More specifically, a page to build the pull request for people. Fields to add text, map preview to drop the pin, and most importantly - previews of the two logos so that it's easy to spot when logos don't have transparent backgrounds! 😉

**Comment by apeltzer** [comment]
Even cooler than just describing what to do ;-)

**Comment by apeltzer** [comment]
To at least jot things down now before we have this in more fancy / webpage / whatever version:


Howto add yourself to nf-co.re webpage:

0.) Ideally fork the repository https://github.com/nf-core/nf-co.re to your own github account. How to do this can be found [here](https://guides.github.com/activities/forking/)

1.) Now go to your own fork of the nf-co.re webpage and modify the YAML file `nf-core-contributors.yaml` with an editor of your choice. 
1.) Please add the details on both you and your institution that you belong to directly to the YAML file above. 

This involves:

- Full Name of the Institution 
- Short Name of the Institution (e.g. an acronym)
- Description (see YAML for examples)
- Address
- URL to website of Institution
- Affiliation: Can be for example department if belonging to big institution (Fancy University is then institution, department would be McFancyDepartment)
- Affiliation URL : Url for the above
- image_fn: Filename for the logo/image you have to upload with the YAML file
- contact: Your Name ;-) 
- contact_email: Your E-Mail
- contact_github: Your github shortname (e.g. mine is apeltzer)
- location in geocoordinates [longitute, latitude]
- twitter: URl to institute twitter account if available

2.) Furthermore, add **two** versions of the institution logo in SVG format you described in the YAML file under `image_fn`:

- one "white" version to the folder `public_html/assets/img/contributors-white`
- one "color" version to the folder `public_html/assets/img/contributors-colour`

These images should both have the _same_ name, e.g. if you have in your yaml a file called `image_fn: foobar.svg`, the files should both be named `foobar.svg` in the respective folders. If you have only raster images available, please search for a SVG versions (wikipedia for example often has SVG versions of logos that can be downloaded and used for example). If you need help with this, please nevertheless follow step 3.) and comment that you have an issue with this. 

The difference between the white and the colour version of images can be seen by looking at examples like this one [here in color](https://github.com/nf-core/nf-co.re/blob/master/public_html/assets/img/contributors-colour/BI.svg) and in [white](https://github.com/nf-core/nf-co.re/blob/master/public_html/assets/img/contributors-white/BI.svg). The reason for this is, that the main nf-co.re webpage has an area where we need a white / transparent version to display properly.

3.) Now that you did the hardest part - please open a [pull request](https://docs.github.com/en/free-pro-team@latest/desktop/contributing-and-collaborating-using-github-desktop/creating-an-issue-or-pull-request#creating-a-pull-request) from _your_ fork that contains the modifications to the `master` branch at https://github.com/nf-core/nf-co.re to get your changes in. This has to be reviewed by anyone from the core team but will usually provide feedback if anything looks weird or isn't properly done - do not hesitate to open the PR, we're not chasing you off if not 100% is perfectly fine ;-)

**Comment by chlazaris** [comment]
Thank you very much @apeltzer!

**Comment by apeltzer** [comment]
You're very welcome - if anything unclear, please write a comment over here and we can get things more appropriately written down & ultimately have a nice little howto for everyone :-)

**Comment by chlazaris** [comment]
Hello @apeltzer. I have just placed the pull request. Please, feel free to let me know if I need to change anything. Thanks again for the detailed howto!

**Comment by jfy133** [comment]
@apeltzer maybe should add to point 4 that you should get permission from institute to display logo... sometime some places can be able special about this without official permission.

**Comment by apeltzer** [comment]
Done by @medulka - thank you!
