### ISSUE TITLE
Map is broken

### ISSUE THREAD

**Issue by ewels** [nf-core/nf-co.re#61]
For some reason, and I have absolutely no idea why, #60 broke the map. Looks like the latitude `16.402660` is being parsed as a string in javascript instead of a number. Whhyyy??

Need to update the javascript to force numeric parsing.

**Comment by matq007** [comment]
Weird, well I should have parsed it properly anyway. JavaScript is a mystery itself sometimes.

**Comment by matq007** [comment]
Fixed #62
