### ISSUE TITLE
Check for duplicate tweets before posting

### ISSUE THREAD

**Issue by ewels** [nf-core/nf-co.re#610]
The automated twitter posts about pipeline releases are great, though sometimes releases can get double-postings (often because of something odd at a user-level with the release I think).

It might be nice to do a simple check before posting a tweet that there isn't already a tweet with identical text. This should avoid the simplest duplicate problems. Or perhaps instead of checking the entire tweet, just check the text at the start: `Pipeline release! nf-core/xxxx xxxx`

**Comment by amyma1** [comment]
I'd like to work on this one for you :)
