### ISSUE TITLE
Have tags that can be clicked on the events webpage

### ISSUE THREAD

**Issue by maxulysse** [nf-core/nf-co.re#634]
**Is your feature request related to a problem? Please describe.**
I find it difficult to simply find all talks (works with any category)

**Describe the solution you'd like**
I'd would like to be able to click on the talk button/tag on the right and sign and only see events that share this tag.

**Describe alternatives you've considered**
Look at the whole list and figure it all by myself...

**Additional context**
A specific tag for the bytesize could be of interest too

**Comment by mribeirodantas** [comment]
This has been already fixed (Example: https://nf-co.re/events)
