### ISSUE TITLE
Add branch protection to TEMPLATE

### ISSUE THREAD

**Issue by MaxUlysse** [nf-core/nf-co.re#638]
I think it would be a good idea to limit the `TEMPLATE` branch for each pipeline to `nf-core-bot`

I actually implemented that in nf-core/sarek, but that's one pipeline, we can and should automatize that for all pipelines.

**Comment by ewels** [comment]
Added in #644 and live at https://nf-co.re/pipeline_health

I've just pressed the magic "Fix all repos" button, so this should now be in place for all pipelines.
