### ISSUE TITLE
Make bytesize / training materials easier to find

### ISSUE THREAD

**Issue by ewels** [nf-core/nf-co.re#692]
Currently the bytesize talks are a little tricky to find - you have to dig through the past events to get to them. This is only going to get more difficult with time.

Would be good to have a page dedicated to videos / training materials / bytesize / something where these are more visible. Would be great to have a search bar to filter them as we get more. Maybe dedicated labels too, eg. those for beginners, DSL2, etc etc.

The homepage video highlight should also be updated to integrate with whatever we build here.

**Comment by MaxUlysse** [comment]
cf https://github.com/nf-core/nf-co.re/issues/634 that is related

**Comment by sofiahag** [comment]
This has already sort of been implemented now, right, on the "Events"-page with the sorting buttons: https://nf-co.re/events

You can just click on "Bytesize" and get the list of links?

It also includes https://github.com/nf-core/nf-co.re/issues/634, right?

**Comment by mribeirodantas** [comment]
You're correct, @sofiahag. I just closed the other issue too. Thanks for checking this out!
