### ISSUE TITLE
Events - video transcripts underneath embed

### ISSUE THREAD

**Issue by ewels** [nf-core/nf-co.re#715]
The event page now automatically creates a YouTube video embed which is great, but now that we have transcripts it would make more sense to put them underneath (and not be hidden in a `<details>` tab).

Ideas:

* Use a HTML comment in the markdown as a placeholder for the embed and use that if found
* Use some other marker for the embed - eg. a horizontal rule with `---` or something?
* Do what WordPress does and look for YouTube URLs by themselves on a line with blank lines above and below, and convert that into an embed. 💯 

I think that the last one is my favourite..

Note that we will still need the yaml frontmatter embed tag so that they show up on the homepage and stuff. So we'll potentially be repeating the YouTube URL quite a lot of times:

1. YAML `youtube_embed`
2. YAML `location`
3. In the text as a bullet / blockquote etc
4. In the text as an embed

But I'm not sure that I can really see an easy way around this without losing flexibility.

**Comment by ewels** [comment]
Tangentally related: https://github.com/nf-core/nf-co.re/issues/673

**Comment by mashehu** [comment]
Implemented in #774
