### ISSUE TITLE
Web launch tool previews JSON with quotes

### ISSUE THREAD

**Issue by ewels** [nf-core/nf-co.re#717]
The web launch final JSON preview wraps non-string entities in quotes. If copied into a params file for Nextflow, this breaks with the new schema validation code as that checks variable types and complains that everything is a string.

Steps to reproduce:

* Clicking _Launch_ on a pipeline such as nf-core/eager
* Fill in the form, setting some boolean and numeric values
* Check the _Launch parameters saved_ page after submission - preview JSON has quotes around booleans and numeric fields:

For example:

```json
{
    "run_bam_filtering": "true",
    "bamutils_clip_half_udg_left": "2"
}
```

Should be:

```json
{
    "run_bam_filtering": true,
    "bamutils_clip_half_udg_left": 2
}
```

If running `nf-core launch --id xxx` to pull these results, they go via the command line tools and the correct types seem to be used in the output JSON (though that has its [own problems](https://github.com/nf-core/tools/issues/976) still!).

**Comment by mashehu** [comment]
oh, I think I fixed the number parsing for the builder, but didn't know that the launch does a similar thing: https://github.com/nf-core/nf-co.re/pull/565/files. We solved the boolean parsing there with: https://github.com/mashehu/nf-co.re/blob/master/public_html/assets/js/nf-core-schema-builder.js#L388-L396. Something similar should work here.

**Comment by mashehu** [comment]
Tested it now and seems to be fixed.
