### ISSUE TITLE
linting integer default of zero produces lint failure

### ISSUE THREAD

**Issue by ggabernet** [nf-core/nf-co.re#759]
## Description of the bug

When setting a parameter of type "Integer" to default of `0`  in the `nextflow_schema.json` (using the nf-core web UI), the `nf-core lint` command interprets it as an error:

```
ERROR    [✗] Pipeline schema does not follow nf-core specs:                                                                                                                                                           
          Default parameters are invalid: '0' is not of type 'integer' 

schema_lint: Schema lint failed: [red][✗] Pipeline schema does not follow nf-core specs: Default parameters are invalid: '0' is not of type 'integer'
```

One example of how this is then saved to the `nextflow_schema.json` is:
```json
                "vprimer_start": {
                    "type": "integer",
                    "description": "Start position of V region primers (without counting the UMI barcode).",
                    "fa_icon": "fas fa-dna",
                    "default": "0"
                },
```

## Steps to reproduce

Steps to reproduce the behaviour:

1. Update the nextflow schema: `nf-core schema build .`
2. Set a parameter to type `integer` and default of zero (0).
3. See error:
`schema_lint: Schema lint failed: [red][✗] Pipeline schema does not follow nf-core specs: Default parameters are invalid: '0' is not of type 'integer'`

## Expected behaviour

Schema lint passing.

## System

- Hardware: Desktop
- OS: MacOS
- Version of nf-core/tools: 1.13.3
- Python version: 

## Nextflow Installation

- Version: 20.10.0

**Comment by ewels** [comment]
Moved to the website repo, as this is not actually to do with nf-core/tools at all (tools is correctly failing with the bad default). Needs fixing in the schema builder code.

**Comment by ewels** [comment]
Reproduced in the web builder - https://nf-co.re/pipeline_schema_builder

![image](https://user-images.githubusercontent.com/465550/116692737-1e779a80-a9bd-11eb-8108-8b91a1a01ceb.png)

In the JSON at the bottom it should be `0` and not `"0"`

**Comment by ggabernet** [comment]
I've also double-checked, as @drpatelh mentioned, when the default in `nextflow.config` for a param is 0, then it has actually no default in the schema. I think this is not ideal, and ideally an actual default of `0` should be displayed.

**Comment by ewels** [comment]
Agreed - that's part of a separate and larger issue though: https://github.com/nf-core/tools/issues/992
