### ISSUE TITLE
Hackathon Subpage?

### ISSUE THREAD

**Issue by apeltzer** [nf-core/nf-co.re#80]
Maybe we should have a section on the webpage where we list some information on upcoming hackathons? I guess its going to happen that we have these quite frequently, so it makes sense to have a central location for these :-)

**Comment by ewels** [comment]
Yes - nice! I think we need a few new sections on the website.. Ones that have been in the back of my mind are:

* General documentation (move away from pipelines - eg. installing nextflow, troubleshooting etc)
* Intro videos
* Events
* Restructure the tutorials a little
* Better intro and docs for the helper tools

Phil

**Comment by apeltzer** [comment]
We could make sub-issues out of some of these actually, now that you improved the way how the webpage is handled in markdown - that should give some beginners also the possibility to help in writing docs for e.g. the helper tools introduction? "General Documentation" is (I think) now solved already 👍

**Comment by ewels** [comment]
We now have an events page. Refactoring documentation for an upcoming PR now.
