### ISSUE TITLE
Update link to nf-core API docs

### ISSUE THREAD

**Issue by ggabernet** [nf-core/nf-co.re#827]
**Describe the bug**
The link to the nf-core API docs for the `Developers` --> `Lint error codes` page should be updated to: `https://nf-co.re/tools/docs/latest/`

Right now it shows an old docs version (1.14dev)

**To Reproduce**
1. Go to `Developers` --> `Lint error codes`

**Comment by mashehu** [comment]
Has been fixed by now.
