### ISSUE TITLE
Update modules documentation for new DSL2 syntax

### ISSUE THREAD

**Issue by drpatelh** [nf-core/nf-co.re#891]
We should update the documentation and existing module references to make sure they are in-line with the new syntax. `modules.config` will be re-factored along with the way that options are passed around the pipeline. The module template will not require a custom `functions.nf` and the main script will be simplified too.

**Comment by mahesh-panchal** [comment]
Hijack. 
- Add suggestions on what to output
e.g. common files (what is common?) , everything, subset.

- Also add information about making modules suitable for offline usage.
E.g. for tools that can auto download datasets (e.g. busco), how to proceed.

**Comment by jenmuell** [comment]
My pull request is now ready for the first review. I scanned and tested the main part of the tutorial but I'm not that familiar with the testing part so maybe someone can read it again

**Comment by jenmuell** [comment]
drpatelh comment:
- [ ] check Nf-core modules README
- [ ] check the Tutorial: Create a DSL2 module
- [ ] check the Guidelines and reference for DSL2 modules

mahesh-panchal comment: 
- [ ] add suggestions on what to output
- [ ] also add information about making modules suitable for offline usage

**Comment by jenmuell** [comment]
I have screened all modules documentation and summarized my oberservations [here](https://docs.google.com/document/d/15nolH2ywwlc9Lw-mX7M8dX8xajv2Z7WX4ZfVar5OkO0/edit?usp=sharing) 
Since I'm not familiar with writing modules I partly couldn't check the guidelines with actual rules. 

The second part of the issue isn't included yet.
