### ISSUE TITLE
Add troubleshooting docs

### ISSUE THREAD

**Issue by apeltzer** [nf-core/nf-co.re#94]
We should try looking at open issues and potential solving points (e.g. missing `mksquashfs`, missing pipeline configuration, singularity bind paths) and add these to the troubleshooting sections as these questions are asked quite frequently either on slack or the github issue trackers. Golden rule:

"Have a FAQ entry for it, whenever something has been asked for >= 3 times!"

**Comment by apeltzer** [comment]
e.g #103

**Comment by ewels** [comment]
Done: https://nf-co.re/usage/troubleshooting
