### ISSUE TITLE
Add button/badge for the nf-core gather.town 'office'

### ISSUE THREAD

**Issue by jfy133** [nf-core/nf-co.re#979]
**Is your feature request related to a problem? Please describe.**
I've set up a [gather.town space](https://gather.town/app/b2RCFGS2cIGusuNi/nf-core-office) to allow for cross-institutional collaboration (meetings/co-coding etc.). It would be nice to 'advertise' this on the website.

**Describe the solution you'd like**
A button/badge like slack/twitter under the `join` page that takes you to the workspace.

**Comment by mashehu** [comment]
Any security/anti-abuse measures we should be thinking of?

**Comment by maxulysse** [comment]
@renbot-bio ?

**Comment by jfy133** [comment]
We _could_ make it invite only or set a password, but this is more complicated to manage.

 At the moment I've just left a noticeboard saying adherence to the code of conduct is required, and contact safety officers in event of any issues.

**Comment by renbot-bio** [comment]
I think we should make it invite only. Safer that way IMO.

**Comment by jfy133** [comment]
OK in that case we have two solutions:

1) add a password, which can be requested somewhere/how on slack? 
2) leave the link 'open' but not advertised, and someone can request being added to the workspace. However this way we can't prevent 'guests' from joining I think... but maybe that gives more flexibility for the people who are already in nf-core?

Then in both cases I guess we shouldn't have a button but rather a note saying something like: 'We also have a gather.town space for meetings and face-to-face interaction. You can request access by asking on slack under #<channel>' or something? What would you prefer? 

The former we could pin on a slack channel somewhere (but this won't be visible). The latter would require more 'maintainence' by us...

**Comment by maxulysse** [comment]
I vote for option 1

**Comment by jfy133** [comment]
Ok we've proceeded to option 1.

I think I would still like to mention it here but less visibily - so I'll make a PR with something to the effect it exists and info can be requested from slack
