### ISSUE TITLE
Add information about how to report version in a local module

### ISSUE THREAD

**Issue by maxulysse** [nf-core/nf-co.re#986]
cf https://github.com/nf-core/tools/pull/1353#pullrequestreview-831601223

**Comment by mashehu** [comment]
Agree, as far as I understand this, this is done locally the same way as for nf-core modules (and it is in the template), so this should be taken care of, but waiting for @maxulysse to chime in.

**Comment by maxulysse** [comment]
Docs were missing. But as @mashehu said it's now clear

**Comment by JoseEspinosa** [comment]
That implementation was fast 😆
