### ISSUE TITLE
First timer setup documentation

### ISSUE THREAD

**Issue by KochTobi** [nf-core/nf-co.re#99]
## Include starter guide steps before forking into nf-core
- [ ] Expect linting error before forked into nf-core

**Comment by ewels** [comment]
How come linting fails before forking? What error do you get?

**Comment by ewels** [comment]
Tests should pass on forks too I think, eg. my fork of the rnaseq pipeline here: https://travis-ci.org/ewels/nf-core-rnaseq/builds/516969382?utm_source=github_status&utm_medium=notification

My guess is that it's not having the `nfcore` docker address perhaps? I wonder if we should make this a warning instead, and a failure only if `--release` is specified..

**Comment by apeltzer** [comment]
That could be the case indeed :-)

**Comment by ewels** [comment]
I think this issue is too vague, I'm not really sure what to do with it, so I'll close it now. If there's something specific that you think should be added, please either open a new issue or better still, a PR 😄
